### ISSUE TITLE
Build fails due to missing gpg key

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#106]
I tried to update for the latest 5.5.4 release, but that failed because the release engineer's code signing key is not on the public key servers. This is not the first time that has happened, and the release process https://wiki.apache.org/solr/HowToReleaseSlowly#Making_a_release does not prescribe adding your key to the public servers either, only to the Apache keys file, so it's no wonder.
And occasionally the key servers are unavailable, which can be hard to debug because we use a pool, so don't always talk to the same server.
Every time there is an issue like this it is a time sink.

So we should probably stop relying on the public key servers, and just rely on the Apache keys file instead. Or possibly fetch the keys file at `update.sh` time and then check it into the repo, and at build time consume it from there. We could also consider removing the GPG verification at build time and just rely on the checksum instead, thus doing GPG verification at `update.sh` time only, not at build time.

**Comment by dsmiley** [comment]
I confess I don't understand why this part of the Dockerfile, the gpg signing, is even there.  Isn't the sha1 verification good enough?

**Comment by makuk66** [comment]
The reason it is in there is because that was recommended as "best" by https://github.com/docker-library/official-images/blob/master/README.md#image-build
From my perspective a couple of things appealed:

- Because the gpg verification is in the Dockerfile it happens at the docker hub build servers -- so even if my workstation/github/CI infrastructure gets compromised, it can be detected there. But I struggle to think of a scenario where such compromise cannot also circumvent the verification.
- If you use gpg instead of the checksum, it might be easier for folks with cloned repos to update without having to run update.sh. But that's a niche use-case, and we do use a checksum so doesn't work.

Personally I think the checksum is sufficient.

**Comment by makuk66** [comment]
I've committed the minimal change for now. If we need to revisit this again, we can

**Comment by tianon** [comment]
Please do revisit this -- the signature and the checksum verify different things.  The signature verifies that the thing we've fetched is indeed published by the folks we expect it to be, where the checksum merely verifies that the bits haven't been tampered with since the checksum was embedded into the `Dockerfile`.

The main reason we prefer to use the keyservers rather than simply downloading the `KEYS` file is that it then also verifies the key itself is what we expect (which we get by using the full fingerprint as has been used in this repository previously); GPG, after fetching the key, will then verify that the key it received actually matches the full fingerprint provided (and we don't get that additional verification with this method -- if someone compromises the Apache distribution server, they can add their own key into the `KEYS` file at the same time as modifying the release tarball).

I'd be happy to make a PR which adds more fallback servers if the GPG fetching is being especially problematic (and to scrape the full list of fingerprints from the upstream `KEYS` file so that they can be embedded), if that would help. :+1:  (including proxying any missing keys to the keyserver gossip pool, which is reasonably trivial to do, and anyone with access to the public key material can do :heart:)

**Comment by makuk66** [comment]
> where the checksum merely verifies that the bits haven't been tampered with since the checksum was embedded into the Dockerfile.

I know, but in your scenario, where an artifact has been compromised, if that happens after we update.sh but before a docker build, then that checksum will change (assuming there is no SHA256ttered attack), and the build will fail before we even get to the GPG verification.

> if someone compromises the Apache distribution server, they can add their own key into the KEYS file

But even with your changes, if the tgz+KEYS compromise is in place before we update.sh, then we just end up using that compromised key, and everything will succeed right? And in the process we post it to the keyservers too which I'm not wild about.

I don't see a good way around that unless we stop blind importing, and instead start recording in the repository what keys we trust (by fingerprint), and call out new ones for explicit external manual verification.

I'm happy with the fallback improvements in your PR.

**Comment by tianon** [comment]
> I don't see a good way around that unless we stop blind importing, and instead start recording in the repository what keys we trust (by fingerprint), and call out new ones for explicit external manual verification.

So, this is actually how we usually handle this in `docker-library` images :smile:
(see https://github.com/docker-library/tomcat/blob/6bcbc1eae9853513c4028ba56bdddd68a00c8962/update.sh#L4-L129 for the `tomcat` example, which I think is probably the most similar)

Implementing that was going to be a somewhat bigger departure from what you've got currently, so I didn't go all the way to that extreme, but I'm happy to take a stab at it if you'd like, or roll back some bits of my own changes here if you'd prefer to implement that (just let me know what you want to keep, or just carve it up -- I don't really care too much either way).  I want to make sure that whatever is implemented is something you're OK with maintaining going forward too. :+1: :heart:

I'm not _as_ worried about the Apache hosting endpoint being compromised directly as I am something in the route between our official build system and Apache's servers, but insulating ourselves from both failure modes is definitely a huge ++ in my book.

From the official images perspective, I'd honestly rather see the GPG code removed entirely instead of simply blindly trusting the `KEYS` file from the same server from which we've downloaded the code and the file signature, but I definitely still see value in continuing to use GPG if you're amenable to it (so I'd rather we not go down that road).

**Comment by makuk66** [comment]
I like that much better, and maintenance would be fine. I guess it's better than simply copying the entire KEYS into the repo because you might pick up some updated expiry or revocations from the key servers. So this approach combined with multiple keyservers would work well.

>  I'd honestly rather see the GPG code removed entirely instead of simply blindly trusting the KEYS file from the same server from which we've downloaded the code and the file signature, but I definitely still see value in continuing to use GPG

Agreed. And I certainly do want to continue using GPG for the verification. But, I still have a question about when. In that tomcat example you don't download the artefact and checksums in the update.sh at all, and thus you have nothing to verify, and thus have to do that at build time, and thus need access to valid keys from keyservers at that point. But in my repo I do the download and gpg verification at update.sh time (and we could check a list of fingerprints there), as well as checksum the artifact, then record the checksum in the Dockerfile for verification there. So if we trust SHA256 to be unbroken, that proves that the bits we download at build time were in fact released by the signaturees, while removing all the gpg pain (the signatures, access to the keyservers, needing a gpg executable in my image) from the Dockerfile. I still think that's a valid approach. But either works, and there's something to be said for being consitent with the other parts of the library, so I'm happy to go your way.

**Comment by makuk66** [comment]
@tianon how about this https://github.com/docker-solr/docker-solr/pull/114/files. I record the fingerprints of the keys used for signing. I store them separately rather than having them mixed in with code. The `update.sh` script helps maintain that by fetching new keys, gives some tips for how to verify those keys. Multiple keyservers are tried both in `update.sh` and the Dockerfiles. I've kept thew separate  gnupg home. I've verified the fingerprints with Shalin and Ishan over direct channels, and Adrien's on http://people.apache.org/keys/committer/jpountz
And the SHA256 is still there too.

I tracked down one source of keyserver flakiness to a local IPv6 network misconfiguration, also fixed.
