### ISSUE TITLE
Permissions on Host Volumes

### ISSUE THREAD

**Issue by jamiejackson** [docker-solr/docker-solr#118]
Back when I was developing my project a couple months ago, I don't remember having any problems with this. (There's a lot I've forgotten, though.)

I'm having trouble writing to a host mount now that I'm pushing this to another docker host.

To troubleshoot, I'm running interactively:

```sh
docker run --rm -it --entrypoint=bash \
  -v /var/docker/solr_test1/data:/opt/solr/data \
  -v /var/docker/solr_test1/credentials:/opt/solr/credentials \
  -v /var/docker/solr_test1/pwd/test1:/opt/solr/server/workaround/pwd \
  -v /var/docker/solr_test1/cores/ask_a_question:/opt/solr/server/solr/mycores/ask_a_question \
  solr-mariadb-baseimage
```
I want to be able to write a config to a volume, but the volume shows as:

```
solr@6f25d0935ded:/opt/solr/server/solr/mycores$ ls -al
total 4
drwxr-xr-x. 3 solr  solr 27 May 12 20:49 .
drwxr-xr-x. 5 solr  solr 93 May  9 22:57 ..
drwxrwxr-x+ 4 10000  990 50 May 12 19:04 ask_a_question
```
And the `solr` user (uid:gid = 8983:8983) can't write inside of it, I think due to the uid/gid mismatches.

I'm not a Docker expert, but I _think_ the images I have used ran their services as root, and maybe I haven't hit that problem yet.

My understanding of this might be completely off-base, but what's the right way to resolve this?

In case it matters, my base image is:

```
FROM solr:5

ENV maria_jar_version=1.5.4
ENV maria_jar=mariadb-java-client-${maria_jar_version}.jar
ENV maria_url=https://code.mariadb.com/connectors/java/connector-java-${maria_jar_version}/${maria_jar}

ENV server_root_path=/opt/solr/server
ENV lib_path=${server_root_path}/lib

ADD ${maria_url} ${lib_path}

# change to root user temporarily for the following RUNs
USER root

RUN chmod a+r ${lib_path}/${maria_jar} && \
  chown solr:solr ${lib_path}/${maria_jar}

################################################################################
# This is all part of an elaborate workaround to
# https://issues.apache.org/jira/browse/SOLR-9725
# Once that ticket's fixed, we won't need this part.
# TODO: Once we've got this Dockerfile dialed in, remove unnecessary packages,
#  like inotify-tools, vim
RUN mkdir -p ${server_root_path}/workaround && \
  touch ${server_root_path}/workaround/hashpwd.txt && \
  chown solr:solr -R ${server_root_path}/workaround && \
  apt-get update && apt-get install -y inotify-tools python vim && \
  curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python && \
  pip install pywatch && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  
COPY workaround/generate_data_config_file.sh \
   workaround/sleep_until_modified.sh \
   ${server_root_path}/workaround/
COPY workaround/workaround_controller.sh  /docker-entrypoint-initdb.d/

RUN chown solr:solr -R ${server_root_path}/workaround
#==============================================================================#

# change the container user back to Solr for future use
USER ${SOLR_USER}
```

**Comment by jamiejackson** [comment]
Looks like https://github.com/docker-solr/docker-solr/issues/33 was about this, too, but it was closed before the host volume question was answered.

Also, I saw https://github.com/moby/moby/issues/2259#issuecomment-228116211, but that thread is long. I'll have to reread it to see if there was a solution buried in it.

**Comment by elyograg** [comment]
Solr committer here.  I don't know much about docker.  The project has not officially produced any docker images.

I will state for the record that it is the intent of the Solr project that Solr should be running as a regular user, not root.  The start script that we include with recent versions will refuse to run as root unless a force option is added to the start command.

There's nothing we in the Solr project can do to prevent any user (or the authors of this container) from running as root if that's what they really want to do, but it's not a good idea.

Reading the other issues referenced by Jamie, I am surprised to see that the solr home is in the program directory -- /opt/solr/server/solr.  Its location can be overridden, and it only needs to contain solr.xml before any cores are created.  Creating cores will require subdirectories in the solr home.

The current location of the solr home inside the program directory (at the location that is default when the program is manually started without specifying the location) suggests that the authors of this image have not paid attention to everything that our service installer shell script does.

The service install script creates an init script that changes to a regular user (default solr) and by default has these settings: solr home at /var/solr/data, program directory in /opt/solr-X.Y.Z, with a relative symlink at /opt/solr pointing to the versioned program directory.

It may be worth noting that if Solr is running in Cloud mode, then configurations are in ZooKeeper, and a new collection can be created entirely with HTTP access once the correct configuration is uploaded to ZooKeeper.  No manual manipulation of directories in the solr home is required, as long as the solr process has write access there.

**Comment by jamiejackson** [comment]
> The project has not officially produced any docker images.

I'll be interested to see how this shakes out, since this project is stated to the official docker image for Solr:

> OFFICIAL REPOSITORY: solr

\- https://hub.docker.com/_/solr/

**Comment by dsmiley** [comment]
> The project has not officially produced any docker images.

I took it to mean that the ASF Lucene/Solr project, as an ASF project, has not done so.  That's kind of moot however, since from a Docker user's perspective, this docker image is official which is apparent from it's simplified name to refer to the image.  Docker Inc can manage its registry as it pleases without anyone's permission.  _Perhaps_ the ASF Lucene/Solr project might wish to produce a docker image (perhaps again by adopting this one as a starting point)... though IMO @makuk66 has done such a fine job that I'm not particularly motivated to suggest any change of course.

This all seems like a great distraction to the actual issue title though.  My apologies to the O.P. for continuing it.

**Comment by makuk66** [comment]
In docker, when you mount a host volume into a container, it will have the uid/gid of the directory on the host.
For example:

```
$ id -u
1000
$ docker run --rm -it -v $PWD:/hi_there ubuntu bash -c "ls -ld /hi_there"
drwxrwxr-x 26 1000 1000 4096 May 15 15:05 /hi_there
$ docker run --rm -it -v $PWD:/hi_there solr bash -c "ls -ld /hi_there"
drwxrwxr-x 26 1000 1000 4096 May 15 15:05 /hi_there
```

If you want to use such a host volume from the solr image,
you need to change its ownership to match what solr runs as,
ie 8983, before you run the docker command.

So I expect the quick fix in your case is to run `chown -R 8983:8983 /var/docker/solr_test1` on the host.
Let me know if that works. I've not gone through your Dockerfile, so if there's more going on let me know and I can dig a little deeper.

> Perhaps the ASF Lucene/Solr project might wish to produce a docker image (perhaps again by adopting this one as a starting point)...

Should that come to pass, please open a separate issue for discussion.

**Comment by jamiejackson** [comment]
> So I expect the quick fix in your case is to run `chown -R 8983:8983 /var/docker/solr_test1` on the host.

That's what I ended doing this morning; thanks for validating. It feels weird to do it this way, but I'm moving forward.

**Comment by raupie** [comment]
I hate having to chown that directory, it's an extra step. I've tried adding my own docker file that creates a user/group for the host uid/gid then add the solr user to the host group so solr can write to the shared volume. This works if the host uid/gid is static (1001) but making it dynamic for any host uid/gid I'm not sure how to do that. This isn't for production but a local development environment so maybe I need to investigate running as root.

**Comment by makuk66** [comment]
Can you expand on your use-case? What does your workflow look like? What does your docker command look like -- How many `-v` are you using and what for? You only have to do the chowning once, just like creating the directory. If you want to do it repeatedly during development, you can easily script a `rm -fr; mkdir; sudo chown; docker run` just how you like it; I do that a lot.

One way around this (which I'm experimenting with a bit; but no promises) is to optionally start the container as root, chown the dirs from the entrypoint inside the container, then use gosu to drop to the `solr` user (or your user) to run the solr server. This is not without its own issues. In that scenario you'd have to explicitly run with `docker run -u 0`, but you should end up with files owned by solr (or your user).

> maybe I need to investigate running as root.

If you do that, with the current image, you end up with root-owned files in your directories.

**Comment by mikebridge** [comment]
I have the same use-case as @raupie, where I'm trying to containerize solr and mount a dev-version of our core so that various users across os-es can run it from docker-compose.  I wasn't able to come up with a good solution---I either had to custom-build a container with the core installed inside it, or else mount the data directory and make it world-writable, neither of which works very well.

```yaml
version: '3.7'

services:
  # ...
  solr:
    image: solr:8.8.1
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - "./solr/data:/var/solr/data"
```

**Comment by makuk66** [comment]
> mount a dev-version of our core

Is that an empty core, or one with data? If the former, the typical approach is to mount the config, then create the core itself at runtime, see [this example](https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset).

> neither of which works very well

What specifically does not work?

**Comment by mikebridge** [comment]
@makuk66 Yes, that example looks similar to what I'm doing in that I pre-create the core in docker, then create a custom image from that:

```Dockerfile
FROM solr:8.8 AS solr
COPY test_core /tmp/test_core
# Debugging
RUN echo "Test Core with Solr 8.8"
```
```
docker build -t my-solr-tmp .
container=$(docker run -P -d my-solr-tmp solr-create -c test_core -d /tmp/test_core)
# create a new image from the running container
docker commit $container my-solr
```

This works OK, but what I really want to do is to use the unmodified official docker-solr image in the same way that I run the official postgresql docker images.  With postgres I just directly point to the official image in docker-compose.yml and then hand it off to a migration framework to finish the database setup.   Then in testing I can I run migrations on a developer machine or in the test environment and I'm ready to go.  This is very maintainable---when I switch to different versions of postgres, all I need to do is edit the version number---there are no setup scripts to maintain or any extra operations code to update.

Ideally I would like to boot the official docker-solr image and hand it off to [haystack](https://django-haystack.readthedocs.io/en/master/installing_search_engines.html#solr).

The problem with the _standalone_ version of solr is that there is no [API command](https://solr.apache.org/guide/8_4/config-sets.html) to create a core.  I understand that this is because it's just not a priority due to [resource limitations](https://lucene.472066.n3.nabble.com/Confusing-error-when-creating-a-new-core-with-TLS-service-enabled-tp4384507p4384675.html):

> You might be wondering why Solr can't create the core directories itself
> using the CoreAdmin API except in cloud mode.  This is because the
> CoreAdmin API is *OLD* and its functionality has not really changed
> since it was created.  Historically, it was only designed to add a core
> that had already been created.  We probably need to "fix" this ... but
> it has never been a priority.  There are bigger problems and features to
> work on.  Cloud mode is much newer, and although the Collections API
> does utilize the CoreAdmin API behind the scenes, the user typically
> doesn't use CoreAdmin directly in cloud mode.

(Here, I tried using a dockerized Cloud version of solr, but haystack doesn't support the admin commands for creating a collection---so I was still stuck in the same place.) 

So if I want to avoid pre-creating an image, I can still work around it by mounting a world-writable `/var/data` volume.  I believe that mounting a "data volume" is better practice with docker anyway, and this is what I'm doing for the dev environment.  This also works _OK_, but I don't like the idea of having a world-writable directory---but the ability to cleanly map of users in docker is quite limited.

**Comment by mikebridge** [comment]
And for added context, this is what I do to set up our solr cores in a Bitbucket Pipeline for as "[service containers](https://support.atlassian.com/bitbucket-cloud/docs/databases-and-service-containers/)" for continuous integration:

```
definitions:
  services:
    solr:
      image:
        name: gcr.io/example-registry/my-solr:0.2.0
        ...
...
```

I could probably also install docker as a bitbucket service and install the cores that way against the native docker-solr image.

**Comment by makuk66** [comment]
In the first part you copy your config into an image, then run the container to create a core with it, then commit that to another image, then presumably run that in your CI. Why not just mount the solr config into your container, and create the core at runtime, in your CI? That way you don't have to make any custom images. 
Perhaps that's what you mean by your "bitbucket service" comment.

BTW, when using standalone solr, use solr-precreate rather than solr-create (see the README) that leads to better logs.

If you don't mount a `/var/solr`, then the created core content will only live as long as the container does, but depending on how you run your CI that may suit just fine. If you do want to keep your content, then yes you need to mount a `/var/solr`, and yes, it will of course need to be writable by the solr user. If you don't want to use a world-writable directory for that, you can chown it to the solr uid instead. Or, avoid mounted directories altogether and use `docker volume` to create a volume (which you can then later copy from if required).
