### ISSUE TITLE
From where are those variables coming from?

### ISSUE THREAD

**Issue by seb63110** [docker-solr/docker-solr#12]
Hi,

Just for my information, can you tell me how can I find the values of ZK_PORT_2181_TCP_ADDR and ZK_PORT_2181_TCP_PORT when launching solr with zookeeper?

thanks

**Comment by makuk66** [comment]
I assume you are referring to the [Can I run ZooKeeper and Solr with Docker Links? ](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#can-i-run-zookeeper-and-solr-with-docker-links) FAQ?

Those variables are provided by docker itself, based on the `--name zookeeper` and  `--link zookeeper:ZK` arguments provided to the `docker run` invocations, and made available to the program running in the container. In our case we refer to them by passing a bash command line in single quotes, so that the interpolation of those variables happens inside the container. Without those single quotes they would be interpolated in the shell that invokes `docker run`, where those environment variables are not present.

See [Legacy container links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) for further explanation.

Do note that this mechanism is now called "legacy", and the ["docker run" docs](https://docs.docker.com/engine/reference/run/) say:

> Publishing ports and linking to other containers only works with the the default (bridge). The linking feature is a legacy feature. You should always prefer using Docker network drivers over linking.

so you may want to try the [Can I run ZooKeeper and Solr clusters under Docker?](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#can-i-run-zookeeper-and-solr-clusters-under-docker) FAQ instead.
