### ISSUE TITLE
Support running as an arbitrary user id

### ISSUE THREAD

**Issue by aclairekeum** [docker-solr/docker-solr#126]
Currently, the solr container fails to run as a random user (random UID) and we should be able to do so. When you try to run as an arbitrary user with UID 10001, fails with the following.
Write log is denied. 
 `whoami: unknown uid 10001
Exception in thread "main" java.nio.file.AccessDeniedException: /opt/solr/server/logs/archived
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.apache.solr.util.SolrCLI$UtilsTool.archiveGcLogs(SolrCLI.java:3542)
	at org.apache.solr.util.SolrCLI$UtilsTool.runTool(SolrCLI.java:3525)
	at org.apache.solr.util.SolrCLI.main(SolrCLI.java:255)
Failed archiving old GC logs
Exception in thread "main" java.nio.file.AccessDeniedException: /opt/solr/server/logs/archived
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.apache.solr.util.SolrCLI$UtilsTool.archiveConsoleLogs(SolrCLI.java:3571)
	at org.apache.solr.util.SolrCLI$UtilsTool.runTool(SolrCLI.java:3528)
	at org.apache.solr.util.SolrCLI.main(SolrCLI.java:255)
Failed archiving old console logs`

**Comment by makuk66** [comment]
What's your use-case? Are you bind-mounting a local directory?

The running server needs to be able to write logs and indices,
so if you want to run with a different user,
you can use volumes with appropriate permissions:

```
$ mkdir mycores mylogs
$ sudo chown 10001:10001 mycores mylogs
$ docker run -p 8983:8983 --user 10001:10001 \
  -v $PWD/mycores:/opt/solr/server/solr/mycores \
  -v $PWD/mylogs:/opt/solr/server/logs \
  solr solr-precreate core1
```

This works, even though the specified user ID is not an actual user in the image.
It is not ideal though. You'll notice and error in the log:

```
whoami: cannot find name for user ID 10001
```

and if you run bash, it will say:

```
I have no name!@c4aef07d67cb:/opt/solr$
```

which is not great.

You would be better off using a custom image and have it add the user,
change ownership of the solr directory, and run as the user:

```
FROM solr:6.6
USER root
RUN groupadd -r -g 10001 group10001 && \
  useradd -r -u 10001 -G 10001 -g 10001 user10001
RUN chown -R user10001:group10001 /opt/solr
USER user10001
```

Do either of those solutions help you?


Now it might perhaps be nice if we included gosu, so you could do something explicit like:

```
$ docker run --user root \
  -v $PWD/mycores:/opt/solr/server/solr/mycores \
  solr bash -c "chown -R 10001:10001 /opt/solr && gosu 10001:10001 solr-precreate core1"
```

or perhaps even something more built into the scripts like:

```
$ docker run --user root \
  -v $PWD/mycores:/opt/solr/server/solr/mycores \
  -e RUN_AS=10001:10001 \
  solr solr-precreate core1
```

Or even always "gosu" solr (always start as root and just default RUN_AS to solr) so you could just:

```
$ docker run \
  -v $PWD/mycores:/opt/solr/server/solr/mycores \
  -e RUN_AS=10001:10001 \
  solr solr-precreate core1
```

These may be worth looking into. But it is a bunch of work, with possible side effects,
and more things for users to learn, and it is non-standard (compared to other images).
And it doesn't address the "missing user" issue, unless you also add the user at run-time.
I'm not conviced it's worth adding that complexity just to avoid a simple one-off
command or a simple Dockerfile.

Another thing we could look at is if/how we can use the Docker User Namespace feature
to address these ownership issues; but I've not had the chance to do so.

**Comment by aclairekeum** [comment]
The use case is using the solr image work with openshift orchestration, which requires a support on starting a container with a random uid,
 which means that we wouldn't know the uid until the container actually starts.

From the openshift doc (https://docs.openshift.org/latest/creating_images/guidelines.html) 

> Support Arbitrary User IDs

By default, OpenShift Origin runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.

For an image to support running as an arbitrary user, directories and files that may be written to by processes in the image should be owned by the root group and be read/writable by that group. Files to be executed should also have group execute permissions.

Adding the following to your Dockerfile sets the directory and file permissions to allow users in the root group to access them in the built image:

I've been able to workaround with the log-write access denied issue by chowning for group 0 but then I still see the error
`whoami: cannot find name for user ID... `

A lot of docker images support starting as an arbitrary user so it'd be good in a longer term to have it added to the solr image as well.

**Comment by makuk66** [comment]
Interesting; thanks for that.
I've taken a stab at it, see https://github.com/docker-solr/docker-solr/pull/130
Can you try `dockersolr/docker-solr:6.6.0-openshift` under OpenShift for me?

Locally this works:
```
mkdir mycores mylogs
docker run -it -e VERBOSE=yes \
  -e USER_NAME=$(id -un) \
  --user $(id -u) \
  -p 8983:8983 \
  -v $PWD/mycores:/opt/solr/server/solr/mycores\
  -v $PWD/mylogs:/opt/solr/server/logs \
  docker-solr/docker-solr:6.6.0-openshift \
  solr-precreate core1
```
which is rather convenient.

I'd still like to understand the user namespace feature better before merging this; just to make sure this implementation does not break better options there.

**Comment by aclairekeum** [comment]
So I am not sure if the USER_NAME env is needed (at least in my case. It could just be uid), but that seems to have this error msg go away. 
`
whoami: cannot find name for user ID 10001
`
Thanks @makuk66 for making the change. Would it be possible to have it in 6.3.0:alpine as well?

**Comment by aclairekeum** [comment]
I think it's more usual to set the USER_NAME be just UID instead of specifying it as 'default,' but not 100% sure on which is preferred over the another

**Comment by makuk66** [comment]
I copied the code snippet from https://docs.openshift.org/latest/creating_images/guidelines.html#use-uid, so it seems to be preferred there. I've seen `user` used too on other forums. I imagine either could in theory conflict with the same username in the base image, which we could avoid with `userUID`. But currently, the base image contains neither `default` nor `user`. Have you come across any other best practice docs on docker.com? We can ask the library team for their guidance too when we get to PR.

**Comment by aclairekeum** [comment]
I've seen some of the docker images worked around by using nss_wrapper. But one downside of it is that the alpine images won't support the nss_wrapper yet(correct me if I'm wrong). So the alpine images should probably need something else for the workaround.

**Comment by jamiejackson** [comment]
What's the status with this (and should either this or #130 be marked as a dupe of the other)?

I ask because it looks like we're going to be using OpenShift, and I'm not sure how problematic this image will be yet. (I was reading through the OS docs, saw the bit about arbitrary UIDs, then realized this image might be problematic.)

**Comment by makuk66** [comment]
> I ask because it looks like we're going to be using OpenShift,

Thanks for letting us know; it's hard to gauge how much interest there is for OpenShift support in this image.

> should either this or #130 be marked as a dupe of the other)?

This issue https://github.com/docker-solr/docker-solr/issues/126 is a bug report. https://github.com/docker-solr/docker-solr/pull/130 is not an issue but a pull request, with some experiments towards solving this bug report. That PR is far behind master though, so needs some updating (or replacing with a new one), and would need to take note of https://github.com/docker-solr/docker-solr/pull/130#issuecomment-325778587.

> What's the status with this

The status is that I'm not wild about the options currently available:
- if we use gosu, then we have to start this container as root, which to me feels like a backwards step given that we've not required that before. But, it does seem a popular approach in docker-library. I've not looked into whether that would work with OpenShift; (and I don't have OpenShift access or a lot of time to spend figuring that out). But I did see somewhere that OpenShift may disallow running as root in which case we'd have a problem. I wonder if we can install gosu, not use it by default, but allow OpenShift users to invoke it somehow. Gosu introduces other questions like should the initdb happen before or after the root drop. Before means you can do chowns which is convenient; after means you run safer.
- if we take the group-0 approach recommended by OpenShift, that is fairly simple, but feels like a bit of a hack, is not done for most other library entries I believe. It could have security implications; and I wonder if this could cause problems in other environments (eg kubernetes, though I think the answer there is no). Perhaps the answer is that we document how you can do this in custom image for OpenShift; but that's not that user-friendly.
- user namespaces I looked into a bit a while back, but it was a bit of a pain and I don't think would help the OpenShift use-case
- I've not heard of a better docker-wide options here.
- while it'd be nice to get OpenShift working, I'm more interested in how these things affect standard Docker installations, e.g. with host-mounted directories. And I'm worried about backwards compatibility with current users of this image.
- All of this is somewhat tied to the larger ongoing discussion in Solr about what lives where, and thus what volumes you want to mount. See eg the discussion here https://issues.apache.org/jira/browse/SOLR-11508

So, all in all I'm not sure what to do here at this time. More experimentation and discussion is required.

**Comment by GrahamDumpleton** [comment]
For what you would need to do to have this work on OpenShift see:

* https://github.com/GrahamDumpleton/docker-solr/commit/a0592c58947ff2f0c5975099dc3ff9058fe91ef6

I have only made changes to the one ``Dockerfile`` just to show what is required. It has been tested by building the docker image from that directory, and deploying it in OpenShift using ``oc cluster up``, without granting any special privileges to the service account the process would eventually run as. IOW, no admin privileges required and can be used by a normal user.

The changes are:

* Have the image use group ``root``, ie., ``gid`` of 0, instead of creating its own special ``solr`` group.
* Fixup permissions on directories that need to be writable so they are group ``root`` and group writable. This is done using the ``scripts/fix-permissions`` script which has been added.
* Make the ``/etc/passwd`` file writable by group so can be updated by process running as group ``root``. An evaluation of doing this has been done and no risks have been found with making ``passwd`` file writable in the context of the running container.
* In ``ENTRYPOINT`` script, if container is run as non ``root`` and non ``solr`` user, add a new entry into the ``passwd`` file for that ``uid``.

The key thing here is running with group ``root``. This makes it possible to handle the case where a docker image is run as a user other than what is defined by ``USER`` and where that user is not in the ``passwd`` file. This scenario is not specific to OpenShift and would occur where ``docker run -u 123123123`` is used.

In that specific case, UNIX will default to running such a process as group ``root``, since no ``passwd`` and ``group`` entry. So if you simply make the default setup also use group ``root`` you can make it work for both cases. There is no risk running it as group ``root``, it doesn't grant the process any special privileges. It is not a hack and is slowly becoming accepted practice for where a platform, or admins, want to enforce that images run as a specified user, overriding what the ``Dockerfile`` says. To ensure portability to platforms which are more secure than typical docker usage, it is highly recommended you use this way of doing things otherwise the issue will keep cropping up more and more as people take security of running docker images more seriously.

Please note I am not a Solr user, and although the image now starts up and I can access the web interface, there may well be other aspects of permissions in the file system that may need to change. I only looked at this due to email on Google Group for OpenShift.

* https://groups.google.com/forum/#!topic/openshift/F920-Ol5c9w

I hope what I show is useful to you.

**Comment by jamiejackson** [comment]
@makuk66, does the docker-solr project have a response to @GrahamDumpleton's reply? It would seem that the solution he offered would solve the problem universally (and not just for OpenShift).

@aclairekeum, what are your thoughts?

**Comment by makuk66** [comment]
Closing this out as this has been addressed in `solr:8`, see https://github.com/docker-solr/docker-solr/commit/6f7a6e812247d00f9f3c293993e26d6d041c119e
