### ISSUE TITLE
Create Solr4 image

### ISSUE THREAD

**Issue by efagerberg** [docker-solr/docker-solr#134]
Although it is pretty old there should be a solr 4 image for use.

This way pysolr and other users can use all docker-solr images for it's automated tests.

**Comment by makuk66** [comment]
Supporting 4 is problematic, because:
- it does not support "solr create", so "solr-create"/"solr-demo" do not work
- it does not have the same config that 5/6 have, so "solr-precreate" does not work
and there may be other issues too, but those are why we never supported it in this repo.
So it would various changes to try and work around those deficiencies, and we'd have to weigh up the ongoing maintenance overhead that would bring. Our aim is to provide an image that allows users to quickly start and use a modern Solr; not to provide all possible older versions.
Especially for a narrow use-case such as automated pysolr testing, where you presumably will be scripting/deploying very specific configurations I think you're better off with a custom Dockerfile.

**Comment by makuk66** [comment]
As I explained above, it's not something we can sensibly do in the current repository.

I've uploaded https://github.com/docker-solr/docker-solr4 as an example for Solr 4; but it has no Docker hub build, far fewer features than the main repo, and won't be supported or updated. But perhaps it gives you a starting point for making your own image.

**Comment by derTobsch** [comment]
@makuk66 thanks for your work! We really appreciate it.
