### ISSUE TITLE
Run commands after solr started

### ISSUE THREAD

**Issue by wmartins** [docker-solr/docker-solr#139]
Hi!

Is there any way to run commands **after** `solr` has started?
I know that I can run scripts before `solr` has started (using `/docker-entrypoint-initdb.d/`). But I need to run them after.

**My Scenario:**

I need to create **many** collection on `solr` startup (if they haven't been created).
I'm using Zookeeper as my cluster manager.

**My Workaround:** (not so elegant)

I created a custom `docker-entrypoint.sh` that starts `solr` and watches (using `tail`) the `solr` PID.

That's it. Let me know if you need more infomation.

**Comment by makuk66** [comment]
> Is there any way to run commands after solr has started?

The general approach for doing custom ordering of the docker-solr startup is to write a script that does what you want, mount that into the container, and execute the script instead of the default `solr` invocation.

> But I need to run them after.

The difficulty with that strategy is that you can only have one program running as the main docker process, and log to output, in a single container. So your choices roughly are:

- start solr in the foreground, but before you do start a background process to run your script. That could use the `wait-for-solr.sh` to wait for solr to get ready, then create your collections. Have your script log somewhere so you can investigate later.
- run your script in the foreground, start solr in the background, create your collections, and then loop slowly until you see Solr die (probably forever). Then rely on solr logs in the logs directory. I think that's less appealing
- run solr in the background, run your script, stop solr and restart it in the foreground, so you end up with Solr as the main process, and logging to stdout, but you still get to see your script output first. That is what https://github.com/docker-solr/docker-solr/blob/master/scripts/solr-demo does, so you could use that as a starting point.

> I need to create many collection on solr startup (if they haven't been created).

If you were doing that with a standalone Solr, I'd recommend just pre-creating the cores before Solr starts in the first place. Either like solr-precreate does, or which explicit external commands to create core directories in a volume before ever starting the Solr container. With Solr cloud and ZooKeeper I don't off-hand know if that would work (ie does Solr recognise the core and create a collection for it?).

But rather than doing it as part of the main Solr container startup, it may be more straightforward to do it externally:
- In whatever script starts your Solr container, give it a few seconds to start up, perhaps wait until Solr is answering on its port, then use `docker exec` into that container to create the collections.
- Or start a second solr container (perhaps from Docker compose) that executes a script that creates the collections in the first through the Solr API

That way your main Solr containers run in a simple unmodified way, and you get explicit logs and error handling in your scripts.

**Comment by wmartins** [comment]
@makuk66 thank you!

`wait-for-solr.sh` is really useful, and I used that on my `docker-entrypoint.sh`.
The example you provided is also great and it also solves the problem!

I'll run more tests to check if everything will behave well using this approach with ZooKeeper.

I think we can close the issue, as the main question was answered! :)
