### ISSUE TITLE
How to create_core in Dockerfile or with docker-compose?

### ISSUE THREAD

**Issue by oppianmatt** [docker-solr/docker-solr#14]
I don't want to have to create_core each time, how do run it as part of the Dockerfile? Can I COPY/ADD some config and have a core ready to go?

**Comment by oppianmatt** [comment]
seems also that solr needs to running to create a core?

My issue is that I want to create a dockerized solr in CI without having to manually create_core.

**Comment by oppianmatt** [comment]
The docs say to create a core you run docker exec which attaches to an existing container instead of docker run which would start a command in a new container. That is needed because solr isn't exporting any volumes. If solr exported the volumes docker run would work.

Issue is that there is no docker exec for docker-compose. There is a docker-compose run but it starts a new container.

The way is to get docker-compose to give the list of service and run docker exec against that:

```
docker exec -it $(docker-compose ps | grep <service> | cut -d" " -f 1) <command>
```

But also people are thinking that create_core is a stand alone command but it's not. It requires solr to be running because it creates cores by making a making a http request like so:


```
http://localhost:8983/solr/admin/cores?action=CREATE&name=foo1&instanceDir=foo1
```

But for those who want to know how to create a core without having a running instance, extend the Dockerfile:

```
FROM makuk66/docker-solr
WORKDIR /opt/solr/server/solr/
ADD . /opt/solr/server/solr/
```

Then you need any directory with a core.properties file (can be empty). And from there have a conf directory with schema.xml and solrconfig.xml. Although with the new autoschema you might not need it.

**Comment by oppianmatt** [comment]
One more small issue is that ADD does not respect USER so you need to chown the files like so:

```
FROM makuk66/docker-solr
WORKDIR /opt/solr/server/solr/
ADD . /opt/solr/server/solr/
USER root
RUN chown -R solr /opt/solr/server/solr
USER solr
```

**Comment by makuk66** [comment]
> I don't want to have to create_core each time, how do run it as part of the Dockerfile? Can I COPY/ADD some config and have a core ready to go?

I'd do it like this: First run up a temporary Solr container and create the core:
```
docker run -d -P --name solr1 solr
docker exec -it --user=solr my_solr bin/solr create_core -c gettingstarted
```
then stop Solr and export the created core directory:
```
docker exec -it --user=solr solr1 bin/solr stop
docker cp solr1:/opt/solr/server/solr/gettingstarted solr1_gettingstarted
```
Then use a custom Dockerfile to build your image:
```
cat > Dockerfile <<EOM
FROM solr
WORKDIR /opt/solr/server/solr/
ADD solr1_gettingstarted /opt/solr/server/solr/gettingstarted
USER root
RUN chown -R solr /opt/solr/server/solr
USER solr
EOM
docker build -t solr-gettingstarted .
```
and try it:
```
docker run -d -P --name solr2 solr-gettingstarted
```
Which sounds somewhat similar to your approach, but I only affect the one core directory rather than the whole solr directory, and I let Solr do its normal creation and re-use that.

**Comment by mehaase** [comment]
Given that Solr doesn't do much of anything without at least one core defined, it would ideal to be able to specify the name of a core in the environment and have that core created when the container starts (if it doesn't already exist). This could be done using something like the "entrypoint script" trick used in some images, like [Postgres official](https://github.com/docker-library/postgres/blob/3f8e9784438c8fe54f831c301a45f4d55f6fa453/9.1/docker-entrypoint.sh).

I could make a proof of concept if it's an idea that you're willing to entertain.

**Comment by makuk66** [comment]
> Given that Solr doesn't do much of anything without at least one core defined, it would ideal to be able to specify the name of a core in the environment and have that core created when the container starts (if it doesn't already exist). This could be done using something like the "entrypoint script" trick used in some images, like Postgres official.

I'm keen on staying close to the upstream distribution's user experience, so that users can use their documentation, and share knowledge between this docker package and standard Solr. And I'm somewhat concerned that this could be a slippery slope where we end up supporting esoteric configurations (the next thing will be "how can I configure the default collection with my schema" etc) that users should perhaps instead address in their own Dockerfiles. But with that caveat, I agree that creating a simple collection would ever so convenient, and is something we should explore. So yes, I'd certainly like to see a PoC.

> Also, what's wrong with running Solr to create a core? I put this in my Dockerfile:
> ...
> This feels simpler and more robust than copying around a whole directory.

I wanted to illustrate where the core information is contained, because the OP was asking about COPY/ADD, and in case you wanted to use them in volumes, and I wanted to have a pristine start of solr in the image. But your way sounds fine too. You might consider removing the logs after the stop, so the user of the image does not get confused thinking they are from their run.

**Comment by makuk66** [comment]
>  I'd certainly like to see a PoC.

Just FYI; I've not forgotten about this. I tried the entrypoint script thing, and have a little demo up where I can do eg:

```
docker run -d -P -v $PWD/myscript.sh:/docker-entrypoint-initdb.d/myscript.sh docker-solr/docker-solr:5.5-alpine
```
where that script contains:
```
#!/bin/bash
COLLECTION=gettingstarted
if [[ -d "/opt/solr/server/solr/$COLLECTION" ]]; then
  echo "$COLLECTION is already present on disk"
  exit 0
fi
OUTPUT=/opt/solr/myscript.out
echo "starting $0; logging to $OUTPUT"
{
until $(wget -O - http://localhost:8983 | grep -q -i solr); do
  echo "solr is not running yet"
  sleep 5
done
echo "solr is running"
if wget -O - 'http://localhost:8983/solr/admin/cores' | grep $COLLECTION; then
  echo "$COLLECTION is already present"
  exit 0
fi
echo creating $COLLECTION core
/opt/solr/bin/solr create_core -c $COLLECTION
echo created $COLLECTION core
} </dev/null >$OUTPUT 2>&1 &
```
which is fairly hacky but seems to work.

Similarly, running: `docker run -d -P docker-solr/docker-solr:5.5-alpine solr-demo` creates a collection and loads the sample data into it. Nice.

I'll check this in on a branch for further discussion; stay tuned.

**Comment by mehaase** [comment]
Sorry I haven't replied earlier. I should have stated in my first post that I view this as a problem in Solr itself: the inability to [create cores over the HTTP API](https://issues.apache.org/jira/browse/SOLR-7316?filter=-2) is what drives my interest in solving the problem in Docker instead. I want to build applications that have multiple containers and can be spun up automatically with Docker Compose. For a containers  like Postgres, I can use the official Docker image because my application connects to the default container and configures it remotely: adding users, changing passwords, and creating database objects. The same is not possible with Solr due to the broken HTTP API, so in every project where I want to use Docker Compose to automate deployment, I need a custom Solr image that creates a specific core.

Hopefully that background explains my motives. As for feature creep, the line can be drawn right here: without a core, Solr isn't usable, and there's no way to create a core without running some additional commands in a shell. If the default image can create a core, however, then a usable container can be built. If users want more configuration than that, they need to customize their own image.

Having said all that, I tried replicating your entrypoint script on my local system and it works quite nicely. :+1: :+1: I changed `COLLECTION=gettingstarted` to `COLLECTION=${gettingstarted:-$COLLECTION}` so that it can be changed at container run time, e.g. `docker run -e "COLLECTION=mycore" ...`.

![screenshot of custom core](https://cloud.githubusercontent.com/assets/320904/14393806/da444d40-fd96-11e5-8adc-61f3d128c989.png)

For backwards compatibility, I foresee other users not wanting a core created by default.

**Comment by makuk66** [comment]
> The same is not possible with Solr due to the broken HTTP API

Can you elaborate what the problem is there?

**Comment by mehaase** [comment]
It's detailed in the [linked Solr bug](https://issues.apache.org/jira/browse/SOLR-7316?filter=-2), but the short version is that creating a core with the HTTP API requires running some shell commands.

**Comment by makuk66** [comment]
@mehaase Have a look at https://github.com/docker-solr/docker-solr/pull/23

**Comment by szipfel** [comment]
Is there a way to specify the config directory within the docker-compose.yml file in the entrypoint section? 

```
solr:
    image: solr:6
    ports:
     - "8983:8983"
    volumes:
      - ./solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - corename
      -conf_dir
```

**Comment by makuk66** [comment]
@szipfel please open new issues for new questions.

The answer to your question is yes. For example, if we copy an example config:

```
$ mkdir myconf mycores
$ docker run -it --rm -v $PWD/myconf:/d solr /bin/cp -r server/solr/configsets/sample_techproducts_configs/conf /d/
```

and then mount it into the container, we can refer to the path we used for mounting.
Eg with a `docker-compose.yml` like:

```
solr:
    image: solr:7.1.0
    ports:
     - "8984:8983"
    volumes:
      - ./mycores:/opt/solr/server/solr/mycores
      - ./myconf:/opt/solr/server/solr/configsets/myconf
    entrypoint:
      - solr-precreate
      - corename
      - /opt/solr/server/solr/configsets/myconf
```

**Comment by szipfel** [comment]
@makuk66 will do. 

Thanks for the response!
