### ISSUE TITLE
Leverage the service installer script included with Solr

### ISSUE THREAD

**Issue by elyograg** [docker-solr/docker-solr#173]
For quite some time now, Solr has included a service installer script.

Looking into the filesystem layout of users who ask for help on the solr-user mailing list with docker images, I have concluded that the layouts, configurations, and scripts were not created by that installer script, but were custom-written.

It would be a lot easier to support users on the solr-user mailing list when they're running docker images if the system layout were more in line with what we expect from a service installation.

Info that may already be known:

The service installer script creates a user (if it doesn't already exist), an init script, a configuration script in /etc/default, and sets the solr home to a location outside of the install directory.

https://lucene.apache.org/solr/guide/7_3/taking-solr-to-production.html#run-the-solr-installation-script

If the service name is set to something custom, such as solr7, then that affects the files and directories that are created.  The service name defaults to solr.  For a service name of solr7, here's what will exist after the service is started:

/opt/solr-X.X.X
/opt/solr7 (a symlink to the directory above)
/var/solr7
/var/solr7/data (this is the solr home)
/var/solr7/logs
/var/solr7/log4j.properties
/var/solr7/solr-8983.pid
/etc/default/solr7.in.sh
/etc/init.d/solr7

Everything in /opt/solr-X.X.X is owned by root.  The regular user (default solr) has no need to write to it.

Many settings can be configured by editing the include script in /etc/default.

A service installed this way can be upgraded by running the new installer with the -f option and all the options used before.  When that is done, the symlink is changed to point to the new version.

Things can get tricky when using the bin/solr script if the service name is not "solr", unless there's an environment variable pointing at the include script.  I'm hoping to improve the scripts so that installed services are found and there's a way to choose one if there are multiple.

https://issues.apache.org/jira/browse/SOLR-9590

Disclaimer: I'm not at all familiar with docker itself, or how you might need to customize things beyond what the installer does in order to accommodate usage in docker.  If you decide to use what we've provided and find problems in the scripts that cause issues for your project, we welcome bug reports, with or without patches.

**Comment by makuk66** [comment]
> For quite some time now, Solr has included a service installer script.
> Looking into the filesystem layout of users who ask for help on the solr-user mailing list with docker images, I have concluded that the layouts, configurations, and scripts were not created by that installer script, but were custom-written.

Our Dockerfiles predate that installation script. The layout in docker-solr is just what is provided by the Solr distribution itself, if you untar it. The decision to do that was motivated by the principle of least surprise, to keep the user experience as close as possible to that of a non-docker user trying out Solr, following the normal documentation. Even today, http://lucene.apache.org/solr/guide/7_3/solr-tutorial.html does not say "first run the service installer script".

We do indeed have some scripts to make running with Docker a bit more practical.

> It would be a lot easier to support users on the solr-user mailing list when they're running docker images if the system layout were more in line with what we expect from a service installation.

I agree that this layout is not particularly appealing. If we do change it, it's going to complicate things for our Dockerfiles and scripts, because they'd have to cope with both layouts, and we cause more confusion in our documentation.

Of course we now have a backwards compatibility problem -- if we just change the layout, we'd break existing docker-solr users. We can wait till the next major version, but I don't quite see Solr 8 on the horizon yet. Perhaps we can do another tag.

So I think next steps is to start a branch, and see what this might look like, then iterate on that. I'll have a go at that, when I have some time.

> Disclaimer: I'm not at all familiar with docker itself

I'd encourage you to experiment with it. It's fun, and a lot of users seem to be looking at deploying Solr that way, so the more comitters are familiar with those use-cases, the better.

**Comment by elyograg** [comment]
Such a major change might indeed be best reserved for a major version upgrade.

If things go the way I have imagined, Solr 8 may have a VERY different filesystem layout than currently exists.  See this issue and its subtask:

https://issues.apache.org/jira/browse/SOLR-6733

If that happens, it would entail similar backward compatibility issues for your image.

**Comment by elyograg** [comment]
I actually don't want to eliminate the cloud distinction.  The idea has come up before, and as someone who primarily uses Solr in standalone mode, scares me a little bit.  If the project as a whole thinks it's a good idea, I won't fight it.

But I do think it would be a good idea to have an identical secondary startup config layout whether that config is in ZK or on the filesystem.  That might simplify the config infrastructure a little bit.

I want to get to the point where there are dead-simple instructions for setting up a fault-tolerant production SolrCloud install on three servers.  Ideally someone could read/follow the same set of instructions whether they use docker-solr or the official distribution, but if they're different because of docker-solr's needs, that won't bother me too much.

I will do what I can on SOLR-6733 to have things work correctly with empty directories.  I think it should be possible to do that.

**Comment by makuk66** [comment]
See https://github.com/docker-solr/docker-solr/pull/204
