### ISSUE TITLE
How to run the solr examples with this docker image?

### ISSUE THREAD

**Issue by schauder** [docker-solr/docker-solr#189]
I'd like to run the examples provided by Solr in the docker container.

So I tried this: 

    docker run --name my_solr -p 8983:8983 -dit solr solr start -e techproducts

With various variations of the `-dit` flags. But every time the examples seem to start up and then exit, causing also the docker container to exit.

So I tried

    docker run --name my_solr -p 8983:8983 -dit solr solr start -f -e techproducts

But this seems to behave the same way, except for an additional warning:

    WARNING: Foreground mode (-f) not supported when running examples.

So my question is: How do I start the Solr examples in the docker image, without immediately exiting the Docker container?

**Comment by makuk66** [comment]
Right, a docker container runs a program, then when that program exits, the container closes. This is really meant for programs that run by themselves in the foreground. The standard Solr examples start one or more servers in the background, so that doesn't map very well to the Docker model. I see that you're supplying `-f`, but the `-e` examples don't pay attention to that.

You could try to work around this by running a command that does not exit, like:
```
docker run --rm -p 8983:8983 -it solr bash -c "solr start -f -e techproducts && tail -f /dev/null"
docker run --rm -p 8983:8983 -it solr bash -c "solr start -f -e techproducts && trap : TERM INT; (while true; do sleep 1000; done) & wait"
```
but it's not ideal.

If you just want to run a Solr up to play with under Docker, search the [README](https://github.com/docker-solr/docker-solr) for `demo`, or look at the other examples there.

 If you want to run the `-e` examples, I'd probably just do that outside docker.

**Comment by mausch** [comment]
There's a `solr-precreate` command now, see https://github.com/docker-solr/docker-solr#creating-cores
