### ISSUE TITLE
How to create Core and Change the Schema with the API through docker-compose?

### ISSUE THREAD

**Issue by alexrun** [docker-solr/docker-solr#192]
@makuk66 Can you show an example of how to add an additional custom script to this docker-compose so I could add new dynamics fields to my Schema?

version: '3'
services:
  solr:
    image: solr:7.5.0
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
volumes:
  data:

**Comment by makuk66** [comment]
Have you seen https://github.com/docker-solr/docker-solr-examples/tree/master/schema-api? Basically, do your schema modification with the API up-front to create the config, then pass the path to the config as an additional solr-precreate argument in your docker-compose.yml

**Comment by alexrun** [comment]
Yes, I've been guiding myself from that URL. But that option requires a two-steps configuration process. I'm trying to make the solr container in one step by combining a script in the docker-entrypoint-initdb.d folder. But my test wasn't successful because apparently, I got into a loop between the creation of the core and the modification of the fields.

**Comment by alexrun** [comment]
It looks like there is a problem with the script.

When the core is been searched

    core_name=$(wget -q -O -  http://localhost:8983/solr/admin/cores|grep -E -o '<str name="name">([^>]+)</str>'|sed -r -e 's/<[^>]*>//' -e 's/<[^>]*>//')
    if [[ -z $core_name ]]; then
        echo "could not determine core name"
        exit 1
    fi

It always returning "could not determine core name"

**Comment by makuk66** [comment]
If you want to do it like https://github.com/docker-solr/docker-solr-examples/tree/master/schema-api-startup, then you need to invoke the script per the example shown at the top of that page; not using docker-entrypoint-initdb.d.

> It looks like there is a problem with the script.

It worked with Solr 6. In Solr 7, a breaking change was made to change the default response format to be JSON instead of the XML. And the type used by the example is not included in the default config. I have updated the script to update that.

In your example you were mounting a data directory under mycores. The script uses Solr's default "create" command, which places the core in the default location, not mycores. I've changed that too.

So now, with a `docker-compose.yml` like:
```
version: '3'
services:
  solr:
    image: solr:7
    ports:
    - "8983:8983"
    volumes:
    - ./data:/opt/solr/server/solr/mycores
    - ./myscript.sh:/myscript.sh:ro
    entrypoint:
    - /myscript.sh
    - -c
    - mycore
```

this appears to works:

```
curl -o myscript.sh https://raw.githubusercontent.com/docker-solr/docker-solr-examples/master/schema-api-startup/myscript.sh
chmod a+x myscript.sh
mkdir data
docker-compose up
```

**Comment by alexrun** [comment]
Thank you @makuk66. Works like a charm.
