### ISSUE TITLE
[Question] Creating an Image with a pre-created core

### ISSUE THREAD

**Issue by HesamKashefi** [docker-solr/docker-solr#223]
I want to create a Solr image with a pre-created core with configurations, my Dockerfile is this:
```
FROM solr:7.7.1-alpine
COPY ./conf /myconfig
RUN ["docker-entrypoint.sh", "solr-precreate", "Packages", "/myconfig"]
CMD ["solr-foreground"]
```
and conf contains default files of a core plus my own schema.xml and solrconfig.xml (which works fine already)

but when I use the command `docker build -t mysolr .` it writes some logs to cmd and never returns back to the cmd to say that image was built...

Am I doing something wrong here?

**Comment by makuk66** [comment]
That `RUN` will run the command during build time. [solr-precreate](https://github.com/docker-solr/docker-solr/blob/master/scripts/solr-precreate#L22) configures the core and then starts Solr -- ie during the build; that's why your build never completes. You should be able to use `/opt/docker-solr/scripts/precreate-core` instead to prepare the core location during the build, and then Solr will create its files at runtime. Note that preparing the core location is fast and cheap; you could easily just do that at runtime too, by just running `solr-precreate` as the `CMD`.

> `FROM solr:7.7.1-alpine`

Note that there is no alpine version anymore; I'd suggest that you're using the `slim` variant (and try Solr 8).

**Comment by HesamKashefi** [comment]
Thanks @makuk66 ,
It's working now...
I thought there is gonna be an alpine version for Solr 8 and I was waiting for that one, because alpine version's size was half of the these new ones...

**Comment by makuk66** [comment]
> I thought there is gonna be an alpine version for Solr 8 and I was waiting for that one, because alpine version's size was half of the these new ones...

No; as a docker library image we can only depend on official library base images, and in the official java image an alpine variant is no longer available.

**Comment by HesamKashefi** [comment]
Thanks, I didn't know that.
