### ISSUE TITLE
Switch to Java12

### ISSUE THREAD

**Issue by qeepcologne** [docker-solr/docker-solr#231]
Main improvement is to switch to shenandoah garbage collector.
I did a lot of manual gc tuning before with g1gc, but for our configuration (64G Heap) switching to shenandoah significantly reduced the number of slow requests.  
We are using it on production for about 6 months since solr 7.6.0 (together with jdk8 shipilev build) and with solr 8.1.1 and jdk12 for some weeks now.

**Comment by makuk66** [comment]
The `docker-solr` Dockerfiles require Debian images. And because it is for the official Docker image, it must use an official base-image from https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links. There is no Java version 12 based on Debian right now. If you run `openjdk:12` you get OpenJDK on Oracle Linux (See https://hub.docker.com/_/openjdk#openjdkversion-from-12-onwards-openjdkversion-oracle-and-openjdkversion-oraclelinux7), which is not compatible with the `docker-solr` repo.

There is an upstream issue asking for a Debian based 12 https://github.com/docker-library/openjdk/issues/302 which is currently open. You may want to indicate your interest by giving a 👍 on https://github.com/docker-library/openjdk/issues/302#issuecomment-482722509.

If that is not forthcoming, we may have to look at porting to Oracle Linux. That then impacts any downstream users who add extra packages: they would have to update accordingly, which depending on what they are adding, could be tricky or impossible. Alternatively we could look at using jlink to create a JRE specifically for Solr, but that sounds like a lot of work with potential problems. That would probably require multi-stage builds (to prevent build time dependencies in the image), which aren't supported in official images (or at least weren't when I last tried), so that's problematic.

So at the moment I'm holding out for an upstream Debian-based 12.

And of course it'd be good to get more data about how well Solr works with 12. Your datapoint is appreciated, but is just one :-)

**Comment by qeepcologne** [comment]
Thanks for the detailed explaination.
At the moment i see 3 alternatives:
- switching to oracle linux: users had to change their images, i can live with that and tomcat did the same.
- skip 12 and go to alpine-13
- use centos and install java-12 from REMI (ok this is not offical jdk base image - i did this for jenkins using the centos image with java-8 and install java-12 in addition)

**Comment by makuk66** [comment]
> switching to oracle linux: users had to change their images, i can live with that and tomcat did the same.

Right. I see [openjdk:12-jdk-oracle](https://github.com/docker-library/tomcat/blob/master/9.0/jdk12/openjdk-oracle/Dockerfile#L1), but also [adoptopenjdk:12-jdk-hotspot](https://github.com/docker-library/tomcat/blob/master/9.0/jdk12/adoptopenjdk-hotspot/Dockerfile#L1) and [adoptopenjdk:12-jdk-openj9](https://github.com/docker-library/tomcat/blob/master/9.0/jdk12/adoptopenjdk-openj9/Dockerfile#L1). But only [openjdk:13-jdk-oracle](https://github.com/docker-library/tomcat/blob/master/9.0/jdk13/openjdk-oracle/Dockerfile#L1); I wonder once 13 is GA we will see adoptopenjdk too.

> skip 12 and go to alpine-13

My reading of https://github.com/docker-library/official-images/pull/5953#discussion_r287565564 is that there will not be an Alpine build for 13 once it becomes GA.

> use centos and install java-12 from REMI (ok this is not offical jdk base image - i did this for jenkins using the centos image with java-8 and install java-12 in addition)

That does not sound ideal.

**Comment by qeepcologne** [comment]
update: oracle linux is not a good option, because oracle linux jdk removed UseShenandoahGC which is (for me) the main improvement, so at the moment i prefer adoptopenjdk:12-jdk-hotspot.

**Comment by makuk66** [comment]
> So at the moment I'm holding out for an upstream Debian-based 12.

I see [the issue asking for that](https://github.com/docker-library/openjdk/issues/302) is now closed. In [the openjdk repo](https://github.com/docker-library/openjdk/blob/master/.travis.yml) I see Debian and slim versions of 13 and 14, and an Alpine for 14 (which may be just because it's the latest, and may not last once 15 happens?), and no 12. On [the README](https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links) and [code](https://github.com/docker-library/official-images/blob/master/library/openjdk) I don't see them yet, but they should be on the way.

[The Solr Ref Guide](https://lucene.apache.org/solr/guide/8_1/solr-system-requirements.html#released-lucene-solr-and-java-versions) says "This version has continuous testing with Java 9, 10, 11, 12 and the pre-release version of Java 13".

So perhaps 13 is the way forward, but it's early days yet.

**Comment by qeepcologne** [comment]
I can live with jdk13-openjdk-oracle + using ZGC instead of Shenandoah.

**Comment by makuk66** [comment]
I made a local custom image with `13-buster` and `docker run -e 'GC_TUNE=-XX:+UnlockExperimentalVMOptions -XX:+UseZGC' testimage` seemed to work here, but I've not done any performance or memory analysis with it. We can try https://github.com/docker-solr/docker-solr/pull/251 from Solr 8.3

**Comment by qeepcologne** [comment]
So thats great news i'm desperately waiting for solr 8.3 release
- java13
- zk 3.5.5 compatible
- annoying logging errors fixed: https://issues.apache.org/jira/browse/SOLR-13293

**Comment by makuk66** [comment]
I've pushed a test build `dockersolr/docker-solr:8.3.0-slim` and `dockersolr/docker-solr:8.3.0`. @qeepcologne want to give them a go?

**Comment by qeepcologne** [comment]
Thanks - i currently try that on staging and let you know if there are issues.
I earlier tried to switch solr 8.2 on live to jdk13, but had to rollback after it was running unstable. I shared my experience with the solr guys and the conclusion is that our configuration (shenandoah + very large heap) is very unusual and the recommendation is to stay on jdk11 + G1GC.

**Comment by makuk66** [comment]
Thanks for trying. I actually merged my PR to master already, before I saw your response, but I can hold off submitting to the library for a little while. I'd be somewhat surprised if jdk13 with the same memory settings was more unstable than jdk11. Is that what you're seeing.

**Comment by qeepcologne** [comment]
Everything is fine with the 8.3+jdk13 image, i using it on staging since 24 hours now.
I just had the jdk13 stability issues on live with (centos 7 + solr 8.2 + shenandoah + large heap), with jdk12 and jdk11 the same memory settings running stable.
I think it's the best to provide both variants: latest (13) and lts (11) based image for solr 8.3.

**Comment by makuk66** [comment]
Thanks for the report.

> (together with jdk8 shipilev build) ... centos 7 ... large heap

Your specific use-case with a large heap and non-standard tuned GC is somewhat advanced and specialised. Per the above it sounds like you're using a custom image anyway. Does it then matter what we do in the official image? You wouldn't be able to use the 13 variant because you've found it unstable, and you wouldn't be able to use 11 variant because it doesn't have shenandoah.

> I think it's the best to provide both variants: latest (13) and lts (11) based image for solr 8.3.

I don't particularly want to add another dimension to the variant matrix; it makes things more confusing for a user to choose, increases the surface of potential gotchas and problems, and makes things slower to build.

Looking elsewhere, [Jenkins](https://hub.docker.com/r/jenkins/jenkins) advertises its own versions LTS and weekly only, and [Elastic Search](https://hub.docker.com/_/elasticsearch) also advertises only versions. [Tomcat](https://hub.docker.com/_/tomcat) has versions with various jvm flavours+versions; but that is very targeted at developers adding their own apps. I think Solr is more like ES and Jenkins than Tomcat.

Your point about 11 being LTS is a good one; perhaps we should just stay on that.

**Comment by qeepcologne** [comment]
Sorry for the confusion, we use docker image for staging and non-dockerized centos installation for live. Use case is to test the same configuration (gc settings, solr/zk combination + jvm) on staging before installing live.
JDK11 from epel/centos is able to use shenandoah.
Jenkins has another dimension (centos, alpine). With centos or ubuntu i can install additional jdks and switch around.
In summary the problem is the debian/oracle ecosystem.

**Comment by makuk66** [comment]
> Maybe we should stay on 11 for 8.x and add latest/unstable in addition for testing. 

I think so too. We could consider building some extra test builds under `dockersolr/` so we can experiment and iterate a bit faster without it requiring library releases, or interfering with them. That will need some work though. Also, maybe around Solr 9 next year would be a good time to reconsider upgrading.

**Comment by makuk66** [comment]
Closing this for now. 8.3 stayed on 11.

Per [wikipedia](https://en.wikipedia.org/wiki/Java_version_history) the next LTS is Java 17, September 2021. That seems a long way away, and we'll see what happens with requirements/compatibility/performance of Solr, and the availability of Java in the docker library. Perhaps we'll find a strong reason to provide multiple JVM variants. If not, it might also be a good principle to restrict major JVM version upgrades to major Solr version upgrades, just to prevent surprises.

**Comment by natereinhardt** [comment]
> Closing this for now. 8.3 stayed on 11.
> 
> Per [wikipedia](https://en.wikipedia.org/wiki/Java_version_history) the next LTS is Java 17, September 2021. That seems a long way away, and we'll see what happens with requirements/compatibility/performance of Solr, and the availability of Java in the docker library. Perhaps we'll find a strong reason to provide multiple JVM variants. If not, it might also be a good principle to restrict major JVM version upgrades to major Solr version upgrades, just to prevent surprises.

OpenJDK 17 has hit "General Availability". I would love to see this conversation opened up again. Seems like a lot of improvements to most GCs has happened from 11->17. Particularly ZGS as been improved and out of experimental. G1 has also had some iterations.

**Comment by goranc** [comment]
What about Solr 8.4 and Java 17, did anyone test that combination with eg. ZGC ?

**Comment by dsmiley** [comment]
I suggest asking questions of this nature on Solr's mailing list: https://solr.apache.org/community.html#mailing-lists-chat
This repo is restricted to Docker aspects.
