### ISSUE TITLE
8.2 on dockerhub

### ISSUE THREAD

**Issue by stuartraetaylor** [docker-solr/docker-solr#237]
Is there any ETA for the 8.2 image being available on hub.docker.com?

Currently 8.1.1 is the latest.

Thanks.

**Comment by qeepcologne** [comment]
I'm also waiting to pull the 8.2 image. I understand that docker hub is somewhat slow/outdated, but why not pushing it on github registry under https://github.com/docker-solr/docker-solr/packages ?

**Comment by makuk66** [comment]
> Is there any ETA for the 8.2 image being available on hub.docker.com?

Yeah I was planning to look into that this week. What happened is that due to https://github.com/docker-solr/docker-solr/issues/238, the fixes prompted by the library team did not get reflected in the official images manifest, leading me to think we were up-to-date already, when that was not the case. So the library team was waiting for me, and I was waiting for them :-) I've fixed that bug, and will push the manifest once the current tests complete; most likely tomorrow.

> why not pushing it on github registry under https://github.com/docker-solr/docker-solr/packages ?

I can do that in this case, but I want to caution you against relying on those packages being up-to-date or accurate (in terms of what the official image will be). They are just test images, and subject to change.

**Comment by makuk66** [comment]
There is now a `dockersolr/docker-solr:8.2` for you to experiment with.
