### ISSUE TITLE
SolrCloud Mounted Volume for Index

### ISSUE THREAD

**Issue by jasi110** [docker-solr/docker-solr#242]
I'm new to Docker.  I start the SolrCloud using the docker-compose.yml and I've added a mounted volume to a Windows folder for the index data as : /c/solr_data:/opt/solr/server/solr.
When I create the collection and then load the data, the index gets populated and is usable.  When I shutdown the containers and start them up again, the index data gets deleted and I get several errors/exceptions in the docker-compose Powershell window.  So I'm a bit confused.

Thank you for any assistance you can provide.

**Comment by makuk66** [comment]
Per https://github.com/docker-solr/docker-solr/blob/master/README.md#running-solr-with-host-mounted-directories, trying mounting it onto `/var/solr`.

**Comment by jasi110** [comment]
Ok.  I changed the volume mount in the docker-compose.yml to /c/solr_data:/var/solr for each of the three solr services, but the index is not be written there.  It gets written to /opt/solr/server/solr.  It seems I need to volume mount to that folder too, but then on startup of the containers, it gets wiped out.

**Comment by makuk66** [comment]
> but the index is not be written there.

Sorry, I was thinking you were using the latest, but I guess you're using [this docker-compose.yml](https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml) which is still on 7. We do have [this one](https://github.com/docker-solr/docker-solr-examples/pull/2) for 8, but unfortunately that's waiting for Solr 8.3, for which there is no ETA. In 8, all the writable data ends up in `/var/solr`, and it's all a bit nicer.

But if you're using 7, then yes, you'd expect `/opt/solr/server/solr` to work, but it doesn't, because solr both stores new files there but also expects existing files there, which there aren't. So you'll see errors like:
```
solr3    | 2019-08-19 14:44:30.032 ERROR (main) [   ] o.a.s.c.SolrCore null:org.apache.solr.common.SolrException: solr.xml does not exist in /opt/solr/server/solr cannot start Solr
```
even on the first invocation.

To fix that, do the windows equivalent of:

```
docker create --rm --name copier solr:7
docker cp copier:/opt/solr/server/solr/ mydir
docker rm copier
cp -r mydir solr1data
cp -r mydir solr2data
cp -r mydir solr3data
```
I tested that with [this docker-compose.yml](https://gist.github.com/makuk66/ab6e4b9cffbfb0ae4a3b76fba567a46d) on macOS, and the server starts properly, and the data is retained. Let me know if that works for you; if it doesn't I can try on Windows. I imagine you may also need to make the zookeeper storage persistent too (see https://docs.docker.com/samples/library/zookeeper/#where-to-store-data), which that compose file doesn't do.

**Comment by jasi110** [comment]
I ran those commands and unfortunately, the index data is still not being written to the host folder.

**Comment by jasi110** [comment]
I actually changed my compose file to use solr 8.2.0 and mounted /var/solr.  I created an index and the files were written to my host as expected.  However, on startup of the SolrCloud today, the index data was deleted.  Same issue that I had with solr 7.

**Comment by jasi110** [comment]
I fixed it!  I needed to persist the ZooKeeper database as you had stated.  I didn't realize the connection.  I found a bug report that if Solr requests the configuration from ZooKeeper and there isn't one, it returns empty, and then Solr acts on that empty and deletes the data.  Not very nice at all.

**Comment by makuk66** [comment]
Oh good. Can you share the ZK volume mounting parts of the docker-compose.yml you used? I'll update the example to include volumes.

**Comment by jasi110** [comment]
Sure.
For zoo1:
volumes:
      - /c/zookeeper_data/zoo1data:/data
      - /c/zookeeper_data/zoo1log:/datalog

For zoo2:
volumes:
      - /c/zookeeper_data/zoo2data:/data
      - /c/zookeeper_data/zoo2log:/datalog

For zoo3:
volumes:
      - /c/zookeeper_data/zoo3data:/data
      - /c/zookeeper_data/zoo3log:/datalog

**Comment by makuk66** [comment]
I've kept this open as a reminder that https://github.com/docker-solr/docker-solr-examples/pull/2 exists and is waiting for 8.3

**Comment by makuk66** [comment]
I've updated and merged https://github.com/docker-solr/docker-solr-examples/pull/2
