### ISSUE TITLE
No Alpine linux builds since 8.0

### ISSUE THREAD

**Issue by rosenbjerg** [docker-solr/docker-solr#257]
There are no releases using Alpine linux, that are newer 8.0, but there are 8.2 builds using other Linux builds, such as Debian

**Comment by rosenbjerg** [comment]
There are Alpine openjdk images here: https://hub.docker.com/_/openjdk?tab=tags&page=1&name=alpine.

**Comment by makuk66** [comment]
The reason is https://github.com/docker-solr/docker-solr/issues/213#issuecomment-501189602 which reflected the situation at the time. You can find more discussion on 
https://github.com/docker-library/openjdk/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+alpine+

See also https://github.com/docker-solr/docker-solr/issues/231 for the thinking for 8.3 which is to use 13.

I still don’t see 13 alpine on https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links

Yes there is a 14 alpine but that is only while it is a ea, afaik.

**Comment by rosenbjerg** [comment]
Okay, I saw that [this one](openjdk:13-jdk-alpine) and thought that might be what was necessary for a Alpine Solr build. It is an official, as far as I know(?)

**Comment by makuk66** [comment]
My understanding is that during the period where the openjdk is an ea, they make an alpine version for it to facilitate testing, and tag it `xx-ea-jdk-alpine` and `xx-jdk-alpine`; but once it stops being an ea, the alpine build is dropped; so you don't get the latest version of the jdk, or security updates  in the alpine base, so really you should not be using that old image for anything important. 

For example, if you look at [13-jdk-alpine](https://hub.docker.com/_/openjdk?tab=tags&page=1&name=13-jdk-alpine) and [13-ea-jdk-alpine](https://hub.docker.com/_/openjdk?tab=tags&page=1&name=13-ea-jdk-alpine), you'll see they both have digest `26ca1df9692d`, which was updated 3 months ago. Compare against [13-slim](https://hub.docker.com/layers/openjdk/library/openjdk/13-slim/images/sha256-ed8f79d4ed10e1e191c2b0810c7062017d5d8e6f9d86927b97ba7666579d6de4) which was pushed 16 days ago.

If correct, I find it unfortunate that the ea-less `13-jdk-alpine` tag is applied in the first place, as it leads to mislead expectations that alpine is in fact supported.

AFAIK, [the README list](https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links) is the truth, regardless of what tags may exist on the hub, so that's what I limit my choice from.

Maybe @tianon can confirm the above is right.

**Comment by rosenbjerg** [comment]
Ah okay, that is indeed very misleading to apply an ea-less tag to an ea build.. But I completely understand your reasoning for not creating a Alpine/Solr build from those.

Thank you for the response

**Comment by rosenbjerg** [comment]
I'll close this issue now :)

**Comment by henrik242** [comment]
FYI: Solr alpine images are here: https://github.com/wodby/base-solr

**Comment by rosenbjerg** [comment]
@henrik242 Cool, thanks a lot! 👍
