### ISSUE TITLE
Found a sustes crypto miner running in my container

### ISSUE THREAD

**Issue by victorsosa** [docker-solr/docker-solr#260]
Hi,

Sad to report that seems like the base image used to build this is contaminated with a crypto malware named sustes that take 100% of the CPU to produce crypto coins

in the dokcerfile you are using:
`FROM openjdk:11-stretch`
and they depends on:
`FROM buildpack-deps:stretch-scm`
and they depends on
`FROM debian:stretch`

for more info here:
https://www.digitalocean.com/community/questions/what-is-this-sustes-in-my-process-in-my-cpu-stats

https://stackoverflow.com/questions/51705317/sustes-in-solr-running-and-using-lots-of-cpu-power

**Comment by makuk66** [comment]
Can you be specific about what have you actually personally observed? Did you see sustes running in one of your containers with ps? Under what user id? Or did you find files in the image that suggest a miner, or miner fetcher is in the image, if so what? Which specific image (tag and image id from `docker image ls`)? And from which registry did you obtain your image? And was this an unchanged image, or one you created a sub image from?
Did you see outbound/inbound non-Solr traffic; if so which IPs?

Was that container exposed to the internet? In that case some Solr CVE may have been used to inject the miner.

I see no mention of this in the https://github.com/docker-library/official-images/issues so I don't expect it's in the base image. And I looked at the current `solr:latest` and I don't see anything obvious there either.

**Comment by victorsosa** [comment]
Did you see sustes running in one of your containers with ps? YES
 Under what user id? 8983 - solr
did you find files in the image that suggest a miner? YES
And was this an unchanged image? YES
Which specific image (tag and image id from docker image ls)?  solr:latest
Was that container exposed to the internet? YES
In that case some Solr CVE may have been used to inject the miner. THIS COULD BE THE ISSUE


Apache SOLR: the new target for cryptominers I WILL CHECK THIS OUT

**Comment by makuk66** [comment]
> docker.io/solr      8                   6946dff5c832        3 weeks ago         818 MB

That is indeed the current one from Docker hub. If you run `docker run -it -u root solr:latest bash` you should see no infection in the image. The version of Solr is 8.2.0.

> Apache SOLR: the new target for cryptominers I WILL CHECK THIS OUT

That link was from last year, and Solr 8.2.0 is not affected by that particular CVE. You can find the latest Solr-related CVEs on [mitre](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=solr). A recent one there was [CVE-2019-0193 about DataImportHandler](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-0193) but that should not have affected 8.2.0 either unless you set `enable.dih.dataConfigParam`.

> Was that container exposed to the internet? YES

From [Solr Ref Guide](https://lucene.apache.org/solr/guide/8_3/securing-solr.html#securing-solr): "No Solr API, including the Admin UI, is designed to be exposed to non-trusted parties. Tune your firewall so that only trusted computers and people are allowed access."

From what you've said so far, the most likely explanation is a post-run external exploit. I'll adjust the issue title.

**Comment by makuk66** [comment]
@victorsosa did you do any more investigation? If not I think we can close this issue

**Comment by victorsosa** [comment]
no more investigation needed this is Solr related issue
