### ISSUE TITLE
Use closest Apache mirror as default download source

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#261]
Today we default to archive.apache.org for pulling Solr tarball, with the option of specifying a `SOLR_DOWNLOAD_SERVER` var.

However the default should be to resolve closest mirror using `closer.lua` and if package not found there, fallback to `www.apache.org/dist` and if not found there fallback to archive.

See https://hub.docker.com/r/harisekhon/hbase/dockerfile for an example from Hbase.

**Comment by makuk66** [comment]
> Today we default to archive.apache.org for pulling Solr tarball, with the option of specifying a SOLR_DOWNLOAD_SERVER var.

That choice was made because we hit various transient and non-transient failures with mirrors, with some mirrors missing new releases that had not yet arrived, or older releases that they chose not to host. This caused lots of failed builds, wasted time, frustration and delayed releases. Archive consistently worked, so that's what I used. Because it is mainly used by docker hub at build time, not by users at run time, it should not provide a heavy load on archive, though I have no metrics to know.

I can't escape the feeling that this day and age you should just use a CDN, host all versions, have a single URL for each version that is served by the CDN's local edge location, rather than force users having to deal with this.

> However the default should be to resolve closest mirror using closer.lua and if package not found there, fallback to www.apache.org/dist and if not found there fallback to archive.

For backwards compatibility the SOLR_DOWNLOAD_SERVER should continue to work if set.

I may have some time to have a shot at this.
