### ISSUE TITLE
Do we need gosu?

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#270]
The usecase for gosu seems a bit odd, can we just remove it? Or at least install via apt instead of wget?

**Comment by makuk66** [comment]
Gosu is perhaps somewhat unusual outside the docker world, but it is used elsewhere in the official library, like [postgres](https://github.com/docker-library/postgres/blob/master/12/Dockerfile#L24), and it is maintained by a docker library team member. See [previous mentions](https://github.com/docker-solr/docker-solr/issues?utf8=✓&q=is%3Aissue+gosu); I put it there for to provide an escape hatch in case you need to do something as root before starting docker-solr under its usual id. It doesn't interfere with normal use, and it's not particularly large, so the main costs are complexity in the Dockerfile (but it's fairly contained) and a longer build time (but that's mitigated by docker layering), and increased attack surface (but this requires you to run it as root, so that can be your considered decision). I have no stats or anecdata of it being used or how, but I don't really want to lose it.

The current installation code was based on examples elsewhere, and vetted by the maintainers. The [installation instructions](https://github.com/tianon/gosu/blob/master/INSTALL.md) now provide an apt alternative for Debian Stretch, which our current FROM images appear to be based on, so we could use that. A disadvantage would be that we could not quickly upgrade to new versions that are not available in the upstream images, but given the functional simplicity and developmental maturity of gosu I don't think that need is likely, and given that it's not commonly used optional tool I don't think it would be a big problem either. Would you like to provide a PR that updates the templates and Dockerfiles?

**Comment by janhoy** [comment]
I see that both gosu and tini are now installable with `apt install gosu tini` so I'll write a PR for them both.
