### ISSUE TITLE
Configuring file indexing in Solr in Docker on RancherOS VM on FreeNAS

### ISSUE THREAD

**Issue by DrLove73** [docker-solr/docker-solr#277]
Hi.
Although I use Linux for more then 10 years, I am new to Docker, I am still on the edges of understanding how this should be used, and I am totally lost how to configure Solr Docker image to index files on FreeNAS file server (running Samba).
So, I would appreciate if someone could walk me through this nightmare.
We use FreeNAS as file server, and since my company for various reasons uses Windows workstations, we have Windows domain and Windows PC's, and for that reason FreeNAS shares are only SMB/Samba. Seams using NFS shares would mess with file permissions.

FreeNAS allows Docker host called RancherOS, so I installed it and here is where I got stuck.
I started by running `sudo docker run -p 8983:8983 -t solr` and when I accessed Solr webconfig, I was not able to create new Core, it informed me something like config files are missing. At that point I checked here and saw you suggested some commands to be run. That is where I got lost and several attempts to create docker container with Core already created failed.

Reading some more, I saw that I should somehow mount my FreeNAS shares inside docker? I initially thought I can give Samba URI to Solr and it will just run with it.

I will try again to create solr container properly, but now I am concerned if I can achieve my goal at all.

1. Does Solr support indexing from Samba share from config, or do I have to mount Samba shares inside docker? In either case please provide further details or maybe commands to achieve this.
2. If I can not mount a Smaba share in Solr docker container, is there some other solution? Maybe additional container or do I have to find a way to mount FreeNAS share with something else?

When I get this initial info, I will probably have more specific info.

Thanks to all who read this, I hope there is someone to point me in right direction.

**Comment by makuk66** [comment]
> I started by running sudo docker run -p 8983:8983 -t solr and when I accessed Solr webconfig, I was not able to create new Core, it informed me something like config files are missing.

I assume it said `Error CREATEing SolrCore 'new_core': Unable to create core [new_core] Caused by: Can't find resource 'solrconfig.xml' in classpath or '/var/solr/data/new_core'`.
Did you note the `instanceDir and dataDir need to exist before you can create the core` message below that? That's a Solr usability issue I'm afraid, the defaults there don't just work. 

That's a large reason why docker-solr has extra scripts to create those directories. See https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores for documentation.

> Does Solr support indexing from Samba share from config, or do I have to mount Samba shares inside docker?
> If I can not mount a Smaba share in Solr docker container, is there some other solution? Maybe additional container or do I have to find a way to mount FreeNAS share with something else?

AFAIK Solr does not have a specific SMB connector. 

To make the data available in the Solr container you either have to connect from the container itself (which would require extra software and config and a custom docker image, and extra privileges), or mount the volume in the linux docker VM, and then use Docker's `-v` directory mapping to make that available that into the container, from where you could then index it.

You _could_ do that from the Solr server container, but it'd be better to use a separate one. Then you can leave the Solr server alone, and iterate on getting your indexer container working how you want.

If you use the solr image for that, you can use its `post` tool to crawl the directories, see [this example](https://github.com/docker-solr/docker-solr/blob/master/README.md#loading-your-own-data).

I don't use FreeNAS/RancherOS, so I can't easily demo that. Best of luck!

**Comment by dsmiley** [comment]
I wouldn't dismiss NFS too eagerly.  Docker expressly integrates with NFS for volume mounts.

Any way, seems like you need to do some high level white-boarding before getting into geeky details.  Solr is often just one component of a larger system.  It seems you want a "product" (e.g. LucidWorks Fusion) and Solr is more of a platform than a product -- in a spectrum with lots of gray.  If you are new to Solr then I suggest playing with Solr without Docker first unless you are already very familiar with Docker.

**Comment by janhoy** [comment]
Agree with david. The kind of project that it sounds to me like you aim for (i.e. Enterprise Search indexing company's file share) is normally complex stuff requiring lots of integration, tuning and work outside Solr. So I'd start with an experienced enterprise search architect and draw up the big picture and decide for components etc. Then, if you still decide on using plain Solr, head over to [Solr's web page](https://lucene.apache.org/solr/community.html#mailing-lists-irc) and engage with the solr-user mailing list for a *much* wider audience for your questions!

**Comment by DrLove73** [comment]
Hmm. The reason I tried with open source tools is because I do not really have a budget for professional tool. We have less then 60 employees and everything we can relocate for IT goes to buying newer workstations.
I was not able to boot CentOS on FreeNAS VM's (it's not KVM but some FreeBSD hypervisor) so I though I could do it via docker.
Oh well, if Solr is just a part of a solution, I will have to see what else is available.

Thank you everyone for your input.
