### ISSUE TITLE
Update Solr 8.4.0 to 8.4.1

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#278]
@dsmiley do you want to give it a shot and test the deploy stuff on mac?

**Comment by dsmiley** [comment]
I will @janhoy .

**Comment by dsmiley** [comment]
FYI we need to remove xml-apis jar from Tika contrib -- see  https://issues.apache.org/jira/browse/SOLR-14054?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17001228#comment-17001228
That has been on my mind and I've been meaning to file a PR.

**Comment by dsmiley** [comment]
That Tika thing is actually for 8.5 so it's a non-issue right now.

I've been following instructions and pushed a PR:
#279 
I've also been watching Martijn's video screen share of the release process:
https://www.youtube.com/watch?v=K0a5lhl28Vg

It's a shame that each build, which builds all versions has to actually download a full Solr .tgz, each of which is around 180MB, sometimes less.  The existence of a "/downloads" with the distributions there doesn't help.  The root cause could be argued this is Solr's problem for being so heavyweight.  Plugin-ification will help.

**Comment by makuk66** [comment]
> It's a shame that each build, which builds all versions has to actually download a full Solr .tgz

There are two downloads:

- the one done by update.sh, which is a one-off, because the files are retained in the downloads folder, where it gets found next time.
- the one done by the Dockerfiles. That one could be resolved with something like https://github.com/docker-solr/docker-solr/issues/140 further discussed in https://github.com/docker-solr/docker-solr/issues/196#issue-392195987 point 7. That was some time ago, so perhaps things have changed. I haven't explicitly discussed this pain point with the library team. The parallel building by Travis, and by Jan's changes, minimise this cost somewhat, but it remains a waste of time, especially on slow links.

 > The existence of a "/downloads" with the distributions there doesn't help. 

I'm not sure what you mean here?

> The root cause could be argued this is Solr's problem for being so heavyweight. Plugin-ification will help.

Well there is always that :-) Improvements there would be appreciated. But I still think there should be a better docker-level option here.

> I've been following instructions and pushed a PR: https://github.com/docker-solr/docker-solr/pull/279

Great!

After https://github.com/docker-solr/docker-solr/commit/d33bed69da61c57f2ddbb5a3a81cc2074842dc27 we should have had an immediate further checkin of the result of `update.sh`, to update the Dockerfiles and so on. I hadn't spotted that was missing. As a result, your diff is much larger than it should have been, affecting all versions rather than just the 8.4.1, and thus making it harder to review. We could fix that by doing that now on master, then rebasing your changes. But I'm not overly worried about it. I have verified that on your branch an `update.sh` shows no further change, which is good.

I'd say go ahead and do the rest of the release process.

**Comment by dsmiley** [comment]
> The existence of a "/downloads" with the distributions there doesn't help.

Sorry I was vague.  By this I meant that it's a shame that the Dockerfile build execution doesn't use the /downloads dir; instead it fetches directly from Apache's mirror.

> I'd say go ahead and do the rest of the release process.

It turns out `generate-stackbrew-library.sh` doesn't work on MacOS (see below); I'll try in Vagrant.
```
[master] docker-solr$ ./generate-stackbrew-library.sh | tee ../new-versions
./generate-stackbrew-library.sh: line 7: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by janhoy** [comment]
> It turns out generate-stackbrew-library.sh doesn't work on MacOS

You have to replace the first line of that script with `#!/usr/bin/env bash` for it to pick up bash5 installed by homebrew. Else it will just use bash3 that ships with macOS.

**Comment by janhoy** [comment]
> it's a shame that the Dockerfile build execution doesn't use the /downloads dir; instead it fetches directly from Apache's mirror

What if we started a 3 line python script that serves all archives in `./downloads` on `http://localhost:8083/<version>/solr-<version>.tgz` and then set `SOLR_DOWNLOAD_SERVER=http://localhost:8983` before runing `build-all.sh`. The SHA and PGP validation will still happen so no harm there.

**Comment by makuk66** [comment]
> What if we started a 3 line python script 

For local use that sounds like a fine idea.

**Comment by janhoy** [comment]
I'll give it a shot

**Comment by janhoy** [comment]
See #281 for a simple solution. Tested it locally and it is really fast :)

**Comment by dsmiley** [comment]
Upstream PR: https://github.com/docker-library/official-images/pull/7301

**Comment by janhoy** [comment]
Closing after release
