### ISSUE TITLE
Release 8.5

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#297]
I volunteer to be RM

**Comment by janhoy** [comment]
Hmm, after merging #296 I continue with the release, but get stuch at

```
./generate-stackbrew-library.sh | tee ../new-versions                                                                                                         ✔  ⚙  10228  11:01:37
failed fetching repo "https://github.com/docker-library/official-images/raw/master/library/openjdk:11-jre-stretch"
tag not found in manifest for "openjdk": "11-jre-stretch"
# this file is generated via https://github.com/docker-solr/docker-solr/blob/96477231f35e50cc9bd8cb0c8e9b004e841a126a/generate-stackbrew-library.sh
```

So openjdk no longer maintains the stretch variant. Does that mean we are *forced* to go to buster @makuk66 ?

**Comment by janhoy** [comment]
My proposal is to change

    FROM=openjdk:11-jre-stretch  --> FROM=openjdk:11-jre
    FROM=openjdk:8-jre-stretch   --> FROM=openjdk:8-jre

That is the way we do for the slim variants already, and it will currently resolve to `buster` since that is what upstream openjdk uses.

**Comment by jaceq** [comment]
Well... this is even more complicated, as actually 'full image' is strech but slim is using: openjdk:11-jre-slim which currently (according to: https://hub.docker.com/_/openjdk?tab=tags&page=1&name=11-jre-slim ) resolves to... buster.

**Comment by janhoy** [comment]
Exactly, it was inconsistent for the 8.4 release. So removing the pinning and instead rely on what upstream has chosen as deault (i.e. what you would get if you `docker pull openjdk:11-jre` or `docker pull openjdk:11-jre-slim`) we get less to maintain. 

I see the problematic part too, that users pulling `solr:8.4` will after this change get auto upgraded to buster next time they pull from hub. But it's is the same with Java minor updates as well. According to https://wiki.debian.org/DebianReleases 'jessie' is EOL 2020 (guess this summer) and the new `stable` release buster is already more than 9 months old and should be a better choice for our users.

**Comment by jaceq** [comment]
That sounds good to me, shall I make a quick PR with this update or is there some longer discussion / approval by @makuk66  needed?

**Comment by janhoy** [comment]
I'll await @makuk66 's response as I'm not that familiar with the generate-stackbrew thing or exactly the requirements of official-images team. We may be allowed to use stretch and work around it but I'd like Martijn's judgement on this. The change is 2 lines so I can commit that as part of the release preparation upstream.

**Comment by makuk66** [comment]
> So removing the pinning and instead rely on what upstream has chosen as default (i.e. what you would get if you docker pull openjdk:11-jre or docker pull openjdk:11-jre-slim) we get less to maintain.

I think that makes sense. I wouldn't want to change from say Debian to some rpm-based bistro, as that is likely to break downstream users, but I'm less worried about stretch-vs-buster issues.

> the requirements of official-images team.

They just want us to use approved upstream images, which these are, so that's all fine.

>  I'm not that familiar with the generate-stackbrew thing 

It's a script that generates the [manifest](https://github.com/docker-library/official-images/blob/master/library/solr) for the library. It just lists the things that they will build and tag, on specific architectures. There is some overlap between this, and the `tools/` scripts docker-solr itself uses to maintain the dockerfiles, in particular [update.sh](https://github.com/docker-solr/docker-solr/blob/master/tools/update.sh), in that they both have to figure out what builds exist. But basically, get `update.sh` working first, and generate the right Dockerfiles in our directories. Then after that generate-stackbrew should just do the right thing; just check its output diff [looks plausible](https://github.com/docker-solr/docker-solr/blob/master/update.md#update-the-official-images-repository) step.

**Comment by janhoy** [comment]
@makuk66 can you please give me maintainer access so I can push to our official-images fork?

**Comment by makuk66** [comment]
I've added the Maintainers group as maintainers, and you're in that group.

**Comment by janhoy** [comment]
8.5 is now available in hub. Thanks for the help with the release everyone!
