### ISSUE TITLE
Creating cores - connection refused

### ISSUE THREAD

**Issue by marcin7848** [docker-solr/docker-solr#302]
**Dockerfile**
```
RUN solr start -p 8983 
RUN solr create -p 8983 -c core1 -d /core1 
RUN solr create -p 8983 -c core2 -d /core2 
RUN solr create -p 8983 -c core3 -d /core3
RUN solr stop -p 8983
```
Could anyone tell me why the above code isn't working ("ERROR: Connect to localhost:8983 [localhost/127.0.0.1] failed: Connection refused (Connection refused)") while the below code is working:

```RUN solr start -p 8983 && solr create -p 8983 -c core1 -d /core1  && solr create -p 8983 -c core2 -d /core2 && solr create -p 8983 -c core3 -d /core3 && solr stop -p 8983```

**Comment by marcin7848** [comment]
Actually, creating cores in that way does not work at all (I mean there is notification in command line that cores was created but when you access web gui you won't see any cores there), it need to be placed in:

```CMD solr start -p 8983 && solr create -p 8983 -c core1 -d /core1 && solr create -p 8983 -c core2 -d /core2 && solr create -p 8983 -c core3 -d /core3 && solr stop -p 8983 && solr start -f```

**Comment by makuk66** [comment]
From https://docs.docker.com/engine/reference/builder/:

> If any build steps change the data within the volume after it has been declared, those changes will be discarded

The solr docker file declares a VOLUME, and you changes happen after that, so will be discarded.

Do core creation at runtime, so that you can create them in mounted volumes. If you want to do it in a custom image, change the entry point to run your script where you create the cores.

If you use the "solr-precreate" command (see https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores), then that will create a core on-disk before starting Solr, so you don't need to start/stop/restart Solr, which makes it faster and less confusing. Look at [how](https://github.com/docker-solr/docker-solr/blob/master/scripts/solr-precreate) that script is implemented, you can see how you could do multiple cores with your own script:

```
precreate-core foo
precreate-core bar
exec solr-fg
```

or run:

```
docker run -it -p 8983:8983 solr:8 bash -c "precreate-core foo; precreate-core bar; exec solr-fg"
```
