### ISSUE TITLE
bashbrew links & install instructions don't work (reliably)

### ISSUE THREAD

**Issue by hossman** [docker-solr/docker-solr#350]
https://github.com/docker-solr/docker-solr/blob/master/update.md currently has two places where it links the the following URL which is a 404...

* https://github.com/docker-library/official-images/tree/master/bashbrew

I suspect bsaed on googling that this should be: https://github.com/docker-library/bashbrew/ ?

The instructions for linix & osx also inlcude links to download & install bashbrew from a jenkins server which (AFAICT) is not reliably onine all the time...

* https://doi-janky.infosiftr.net/job/bashbrew/job/master/lastSuccessfulBuild/artifact/

...perhaps these links should instead point to https://github.com/docker-library/bashbrew/releases ?

**Comment by dsmiley** [comment]
Good suggestions!  Ishan recently had to update a dead link on that page too.

This is a great teachable moment on how to use GitHub.  When viewing the update.md online, see the edit link icon shaped like a pencil.  You can make your suggestion right there on the page... and then the saving process is really a fork + PR that is automated for you.  At that juncture you can add some comments as to why you are doing this (i.e. what you said above).  PRs rarely need an "issue" because a PR can be thought of as an enhanced issue.  It's an issue (title, description, commentary, other metadata) + code.
