### ISSUE TITLE
CVE-2021-44832 requies update of log4j

### ISSUE THREAD

**Issue by rahulverma** [docker-solr/docker-solr#407]
According to [CVE-2021-45046](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832) a remote code execution attack is still possible. The recommendation is to update log4j to 2.17.1. I do not see it mentioned in [Security Bullitin](https://solr.apache.org/security.html). Can we still update this jar in the docker image ?

**Comment by dsmiley** [comment]
The title of this issue is to 44832. Indeed, this one isn't referenced in the bulletin or the linked false-positive list: https://cwiki.apache.org/confluence/display/SOLR/SolrSecurity#SolrSecurity-SolrandVulnerabilityScanningTools I will go add it to that list.  If you read https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832 it has to do with a JdbcAppender.  Solr's default logging configuration does not use that, and furthermore in my decades of Java experience, it's very rare for someone to go out of their way to use these obscure logging appenders.  It's not common/expected.

The CVE in your description, 45046, is referenced in the security bulletin and explained in the false-positive list.
