### ISSUE TITLE
Create multiple cores not working with dockerfile

### ISSUE THREAD

**Issue by kauanmocelin** [docker-solr/docker-solr#409]
I'm trying to create multiples cores and run solr server using a dockerfile but I can't understand why this not working:

```FROM solr:8.11.1
COPY --chown=solr:solr security/security.json /var/solr/data/security.json
COPY colos_configs /opt/solr/server/solr/configsets/colos_configs/
COPY tos_configs /opt/solr/server/solr/configsets/tos_configs/
ENTRYPOINT ["bash", "-c", "precreate-core solr-core-tos /opt/solr/server/solr/configsets/tos_configs; precreate-core solr-core-colos /opt/solr/server/solr/configsets/colos_configs", "exec solr -f"]
```
With the command above cores are created ok but server not ran, the container die after create cores. Why "exec solr -f" not run after core creation?

PS: I did it work using docker-compose using the "same" command in ENTRYPOINT but I really want understand this behavior.

**Comment by HoustonPutman** [comment]
because your command is `bash`, giving it a command string given in your 3rd parameter. If you want to run `exec solr -f` last, then add that to the end of your 3rd parameter.

ENTRYPOINT ["bash", "-c", "precreate-core solr-core-tos /opt/solr/server/solr/configsets/tos_configs; precreate-core solr-core-colos /opt/solr/server/solr/configsets/colos_configs; exec solr -f"]
