### ISSUE TITLE
Extending base image

### ISSUE THREAD

**Issue by crazycodr** [docker-solr/docker-solr#46]
I'm relatively new to this docker thing and we are dockerizing our app. One of our components is a solr server. We need to add files to the docker image and create a volume for the data to be backed up easily. Below is our Dockerfile i built but i'm not sure if i got it right, can you help us?

```dockerfile
FROM solr
MAINTAINER Learning Bird Development <lbdev@learningbird.com>

# Add mysql connector
RUN mkdir /opt/solr/contrib/dataimporthandler/lib
ADD mysql-connector-java-5.1.39-bin.jar /opt/solr/contrib/dataimporthandler/lib/mysql-connector-java-5.1.39-bin.jar

# Add default app core configuration
ADD app /opt/solr/server/solr/mycores/app

# Declare the volume for solr app core data
VOLUME /opt/solr/server/solr/mycores/app/data

# Expose solr port
EXPOSE 8983

# Set the current working dir to the core
WORKDIR /opt/solr

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-precreate", "app"]
```

**Comment by makuk66** [comment]
By defining the VOLUME in the Dockerfile, docker will at runtime create a volume and mount it there. The content of the volume is then accessible from the host, and you could back up from that. For example:

```
$ docker create  issue46 .

$ docker run -P -d --name issue46-1 issue46

$ docker exec -it -u root issue46-1 bash -c "touch /opt/solr/server/solr/mycores/app/data/foobar"

$ docker inspect -f {{.Mounts}} issue46-1
[{54f2b32802096c5757aeae813b28775a46c0af20b0a9db5accb3f35fcd362e0d /mnt/vms/docker/docker/volumes/54f2b32802096c5757aeae813b28775a46c0af20b0a9db5accb3f35fcd362e0d/_data /opt/solr/server/solr/mycores/app/data local  true }]

$ sudo ls -l /mnt/vms/docker/docker/volumes/54f2b32802096c5757aeae813b28775a46c0af20b0a9db5accb3f35fcd362e0d/_data/foobar
-rw-r--r-- 1 root root 0 Aug 23 13:40 /mnt/vms/docker/docker/volumes/54f2b32802096c5757aeae813b28775a46c0af20b0a9db5accb3f35fcd362e0d/_data/foobar
```
but there is a problem with ownership here. If you run `docker logs issue46-1` you see that Solr failed to write to the directory, because it was owned by root:

```
$ docker exec -it -u root issue46-1 bash -c "ls -ld /opt/solr/server/solr/mycores/app/data"
drwxr-xr-x 2 root root 4096 Aug 23 13:01 /opt/solr/server/solr/mycores/app/data
```

You can work around that by changing your Dockerfile to have:

```
ADD app /opt/solr/server/solr/mycores/app
USER root
RUN chown -R solr:solr /opt/solr/server/solr/mycores/app
USER solr
RUN mkdir /opt/solr/server/solr/mycores/app/data
```

with that, you get:

```
$ docker run -P -d --name issue46-1 issue46

$ docker exec -it -u root issue46-1 bash -c "ls -l /opt/solr/server/solr/mycores/app"
total 8
drwxr-xr-x 3 solr solr 4096 Aug 23 13:06 conf
-rw-r--r-- 2 solr solr    0 Aug 23 12:14 core.properties
drwxr-xr-x 2 solr solr 4096 Aug 23 13:06 data

$ docker inspect -f {{.Mounts}} issue46-1
[{3eafeec8a1ebdc16dfc454586e9d75497b1c8801ed287f3ea104a405f22ee20b /mnt/vms/docker/docker/volumes/3eafeec8a1ebdc16dfc454586e9d75497b1c8801ed287f3ea104a405f22ee20b/_data /opt/solr/server/solr/mycores/app/data local  true }]

$ sudo ls -l /mnt/vms/docker/docker/volumes/3eafeec8a1ebdc16dfc454586e9d75497b1c8801ed287f3ea104a405f22ee20b/_data
total 8
drwxr-xr-x 2 8983 8983 4096 Aug 23 14:06 index
drwxr-xr-x 2 8983 8983 4096 Aug 23 14:06 tlog
```

But depending on your use-case, creating your own image may not be needed at all; instead you can provide configuration at runtime with an unmodified image. See:

- [How do I persist Solr data and config?](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#how-do-i-persist-solr-data-and-config)
- [How can I mount a host directory as a data volume?](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#how-can-i-mount-a-host-directory-as-a-data-volume)
-  [How can I use a Data Volume Container?](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#how-can-i-use-a-data-volume-container)

**Comment by crazycodr** [comment]
Thanks, we solved all that quite some time ago and have a full docker dev/prod environment running. Thanks again for the followup!
