### ISSUE TITLE
Can't use "solr zk" ?

### ISSUE THREAD

**Issue by dsmiley** [docker-solr/docker-solr#71]
I'd like to use the zk upload capability.  I know this isn't the complete invocation but if I run this:

```
$ docker run --rm solr zk
```

I get:
/opt/docker-solr/scripts/docker-entrypoint.sh: line 131: exec: zk: not found

And if I try:

```
$ docker run --rm solr solr zk
```

I get:
ERROR: zk is not supported by this script

Usage: solr start ....etc

**Comment by makuk66** [comment]
Yeah, that's not ideal. We'll have to think about how best to fix that.

In the meantime, as a workaround you can do:

```
docker run -it solr bin/solr zk
```

**Comment by makuk66** [comment]
@dsmiley Have a look at that PR; I think this is probably as good as we can make it: if you want to run solr as a server as intended, you can omit the command name. If you want to run solr for some other purpose, you'll have to specify the "solr" command explicitly (so you end up with "solr solr") and provide whatever arguments you desire.

This is a possibly breaking change: for users who currently run with "docker run solr solr" and rely on the `-f` being provided will be caught out. I'm not too happy about that.

I'm also not entirely wild about this use of the solr command. A lot of the help text and documented use cases make assumptions about this command operating on the local Solr -- which there isn't here because you're in a container that is separate from any other. Most commands won't make any sense in this context (eg stop, restart, status) and others that do (eg zk healthcheck) will need special arguments to connect to the right zookeeper/solr server. So is this actually useful?

**Comment by dsmiley** [comment]
FYI I'm at LSR conf and will look closer when I get back; perhaps over the weekend.  But in essence... my use-case is with mounting a volume to where my config is on disk.  Users should be able to do this stuff purely with Docker without having to download a Solr distribution the non-Docker way.

Once I figured out I could do `bin/solr` I was happy... it was just non-obvious and it took some poking around to figure this out.

**Comment by dsmiley** [comment]
The PR LGTM.

**Comment by dsmiley** [comment]
BTW, I have no convictions on the best way to solve this issue but I thought I'd mention that I think a fine approach is simply to return a helpful error message if a known command is invoked in an unsupported way.  That may be the easiest and perhaps involves the least "magic"; not sure.
