### ISSUE TITLE
Using SOLR by docker remote API

### ISSUE THREAD

**Issue by antxa** [docker-solr/docker-solr#87]
I want to call SOLR by docker's remote API. I have checked different possibilities to persist data and config in Docker Solr FAQ, but I'm not sure which is the best in my case that I'm using remote API calls.
I guess the best option is to mount a host directory as a data volume, and then specify the next info in the containers/create POST request:
"Volumes": { }
"HostConfig": {
         "Binds": ["hostdir:targetdir]
But I'm not sure what directories do I have to specify in those volume configurations. I don't know neither if it is better to pre-create or create an index (I want to use my own schema and solrconfig)

**Comment by makuk66** [comment]
> I want to call SOLR by docker's remote API

Out of interest -- why through the API?

> I guess the best option is to mount a host directory as a data volume,

You can do that, if you can create that host directory (and chown its permissions) ahead of time. But if you can do that on the host, why do want to use the API rather than the CLI? If you're trying to isolate yourself from the docker host, you might be better of creating a volume for it with the volume API. 

> But I'm not sure what directories do I have to specify in those volume configurations

Example:

```
mak@cylon:~$ cat > create.json
{
       "Image": "solr:6.3",
       "HostConfig": {
         "Binds": ["/home/mak/mycores:/opt/solr/server/solr/mycores"],
         "PublishAllPorts": true
      }
}
mak@cylon:~$ curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" -X POST -d @create.json http://localhost:2375/containers/create
{"Id":"760aedb41556b93a271099db6042d377062c763438bb336f3edccf363bb2540e","Warnings":null}
mak@cylon:~$ curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" -X POST http://localhost:2375/containers/760aedb41556b93a271099db6042d377062c763438bb336f3edccf363bb2540e/start
mak@cylon:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
760aedb41556        solr:6.3            "docker-entrypoint.sh"   18 seconds ago      Up 3 seconds        0.0.0.0:32768->8983/tcp   angry_jones
```

> I don't know neither if it is better to pre-create or create an index (I want to use my own schema and solrconfig)

It kinda depends on where you're starting from.
If you already have a core setup how you like somewhere else, just copy that to a bind-mounted directory in eg `/opt/solr/server/solr/mycore`. If you have just the configset you want to use, but want to create the core with a container, see https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores: use one bind-mount volume to pass in a config directory, and another to store the core. I'd suggest you experiment with the CLI first before then replicating it with the API.

Are your schema and solrconfig in a repo somewhere?
