### ISSUE TITLE
Custom SOLR_HOST

### ISSUE THREAD

**Issue by shadow-fox** [docker-solr/docker-solr#88]
If I am spawning multiple solr container using the same image, how would I change the SOLR_HOST variable in the bin/solr.in.sh. As lets say I have solr1, solr2 solr3 as my docker container, I want all these to use the SOLR_HOST like the following:
solr1 -> SOLR_HOST=solr1
solr2 -> SOLR_HOST=solr2
solr3 -> SOLR_HOST=solr3

I have already created a new DockerFile to change some params in the solr.in.sh but for this I am not able to do the change other than creating 3 different DockerFile for each container. 

Another issue is, whenever I try to restart the solr service, the docker container gets stops, as it sends the stop signal and then the docker container stops. How would the server be restarted along with the changes in the solr.in.sh ?

**Comment by dsmiley** [comment]
Starting with Solr 6.3, solr.in.sh is completely commented out so that environment variables override it.

RE restart: not sure.

**Comment by risdenk** [comment]
@shadow-fox you can change the solr host with `-h` on the `bin/solr` script. I've done this before so you can easily change what address gets registered in Zookeeper. Usually I do this by changing the command that gets run.

**Comment by shadow-fox** [comment]
@dsmiley I am using 6.2.1 version. Any pointer on how would I write a new script to actually handle restart ? 
@risdenk I am using docker-compose yaml file. Here I have already set container_name and hostname but it never gets updated in the solr.in.sh script and hence it only registered with the container id. 
I have tried to use the same with the solr:latest image, but it didnt update, here is the container bin/solr.in.sh 
https://gist.github.com/shadow-fox/9110bba1b92506fc20ced4a218bcee5b

**Comment by shadow-fox** [comment]
The docker-compose.yml and DockerFile is here:

**Comment by risdenk** [comment]
in your docker-compose.yml file you can add something like this:

```
command: bin/solr -f -c -z YOUR_ZK_STRING -h YOUR_HOSTNAME
```

I that would start Solr in cloud mode, in the foreground, with your ZK string (so you don't have to build your own image), with your specific hostname.

**Comment by makuk66** [comment]
> How would the server be restarted along with the changes in the solr.in.sh ?

If you `docker kill` the container (or the JVM exits), a `docker start` will restart it. This maintains the environment, and the disk. https://docs.docker.com/engine/admin/host_integration/ will even do it for you.

The easiest is to use environment variables, rather than modifying `solr.in.sh`, like @dsmiley said. And if you can get by with command parameters like @risdenk's example, even better.

But for completeness: if you do want to modify your `solr.in.sh`, you could perhaps do so from a docker_entrypoint.d script. Or just mount a script which makes the modification (but take care to only do that once) and then runs solr, then mount that script and specify it as the command to run when running the container. Or copy the `solr.in.sh` to your docker host, modify it there as you want, then bind mount it into place in the container. 
You should not need to use your own Dockerfile at all.

**Comment by shadow-fox** [comment]
@makuk66 I followed @risdenk's that solved the purpose.
