### ISSUE TITLE
Service 'solr' failed to build: lstat scripts: no such file or directory

### ISSUE THREAD

**Issue by jlr2k8** [docker-solr/docker-solr#91]
### Expected behavior
`Step 18/25 : COPY scripts /opt/docker-solr/scripts `should work and continue onto next step

### Actual behavior
```
Step 18/25 : COPY scripts /opt/docker-solr/scripts
ERROR: Service 'solr' failed to build: lstat scripts: no such file or directory
```
Installation fails

### Information

```
downloading https://archive.apache.org/dist/lucene/solr/6.3.0/solr-6.3.0.tgz
downloading https://archive.apache.org/dist/lucene/solr/6.3.0/solr-6.3.0.tgz.asc
/opt/solr.tgz: OK
-rw-r--r--    1 root     root     146004505 Nov  2 16:33 /opt/solr.tgz
-rw-r--r--    1 root     root           819 Nov  2 16:33 /opt/solr.tgz.asc
gpg: Signature made Wed Nov  2 14:25:42 2016 UTC using RSA key ID 177050F6
gpg: Good signature from "Shalin Shekhar Mangar (CODE SIGNING KEY) <shalin@apache.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 38D2 EA16 DDF5 FC72 2EBC  433F DC92 616F 1770 50F6
 ---> 66ca4900dc2f
Removing intermediate container 67bbacac2aa7
Step 18/25 : COPY scripts /opt/docker-solr/scripts
ERROR: Service 'solr' failed to build: lstat scripts: no such file or directory
```

### Steps to reproduce the behavior

Run `docker-compose up -d` against latest Dockerfile (6.3.0 latest)

**Comment by makuk66** [comment]
The error is:

```
ERROR: Service 'solr' failed to build: lstat scripts: no such file or directory
```

Did you perhaps copy the Dockerfile to another directory and try to build there? That won't work; you need to have the local `scripts` directory to copy into the image during the build. So either just build in its normal place, or copy the scripts directory to your new location.

If you see this error while building in the usual place, then perhaps you have mistakenly deleted the scripts directory. If you're in the usual place, and the scripts directory exists, then I'd be very surprised, because the build service runs fine (See https://travis-ci.org/docker-solr/docker-solr#L1910). Conceivably be a docker behaviour change; what version of docker are you running?

And what do you mean by `Run docker-compose up -d against latest Dockerfile`? You run `docker-compose` against a `docker-compose.yml` file, not a `Dockerfile`.

**Comment by jlr2k8** [comment]
Sorta. I needed to run a `docker pull solr` again (derp). Moving the `Dockerfile` around didn't cause problems before that, so that doesn't seem relevant.

The `Dockerfile` is what is used to define the app's environment - the instructions for the build - and is used by `docker-compose.yml`

I'll admit my word choice (against) was off, but hope I didn't confuse you ;)

Anyways, thanks for your insight.
